// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hls_LK.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int hls_LK::C_S_AXI_DATA_WIDTH = "100000";
const int hls_LK::C_S_AXI_WSTRB_WIDTH = "100";
const int hls_LK::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic hls_LK::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<8> hls_LK::ap_const_lv8_0 = "00000000";
const sc_lv<1> hls_LK::ap_const_lv1_0 = "0";
const sc_logic hls_LK::ap_const_logic_0 = sc_dt::Log_0;

hls_LK::hls_LK(sc_module_name name) : sc_module(name), mVcdFile(0) {
    hls_LK_CONTROL_BUS_s_axi_U = new hls_LK_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>("hls_LK_CONTROL_BUS_s_axi_U");
    hls_LK_CONTROL_BUS_s_axi_U->AWVALID(s_axi_CONTROL_BUS_AWVALID);
    hls_LK_CONTROL_BUS_s_axi_U->AWREADY(s_axi_CONTROL_BUS_AWREADY);
    hls_LK_CONTROL_BUS_s_axi_U->AWADDR(s_axi_CONTROL_BUS_AWADDR);
    hls_LK_CONTROL_BUS_s_axi_U->WVALID(s_axi_CONTROL_BUS_WVALID);
    hls_LK_CONTROL_BUS_s_axi_U->WREADY(s_axi_CONTROL_BUS_WREADY);
    hls_LK_CONTROL_BUS_s_axi_U->WDATA(s_axi_CONTROL_BUS_WDATA);
    hls_LK_CONTROL_BUS_s_axi_U->WSTRB(s_axi_CONTROL_BUS_WSTRB);
    hls_LK_CONTROL_BUS_s_axi_U->ARVALID(s_axi_CONTROL_BUS_ARVALID);
    hls_LK_CONTROL_BUS_s_axi_U->ARREADY(s_axi_CONTROL_BUS_ARREADY);
    hls_LK_CONTROL_BUS_s_axi_U->ARADDR(s_axi_CONTROL_BUS_ARADDR);
    hls_LK_CONTROL_BUS_s_axi_U->RVALID(s_axi_CONTROL_BUS_RVALID);
    hls_LK_CONTROL_BUS_s_axi_U->RREADY(s_axi_CONTROL_BUS_RREADY);
    hls_LK_CONTROL_BUS_s_axi_U->RDATA(s_axi_CONTROL_BUS_RDATA);
    hls_LK_CONTROL_BUS_s_axi_U->RRESP(s_axi_CONTROL_BUS_RRESP);
    hls_LK_CONTROL_BUS_s_axi_U->BVALID(s_axi_CONTROL_BUS_BVALID);
    hls_LK_CONTROL_BUS_s_axi_U->BREADY(s_axi_CONTROL_BUS_BREADY);
    hls_LK_CONTROL_BUS_s_axi_U->BRESP(s_axi_CONTROL_BUS_BRESP);
    hls_LK_CONTROL_BUS_s_axi_U->ACLK(ap_clk);
    hls_LK_CONTROL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    hls_LK_CONTROL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    hls_LK_CONTROL_BUS_s_axi_U->ap_start(ap_start);
    hls_LK_CONTROL_BUS_s_axi_U->interrupt(interrupt);
    hls_LK_CONTROL_BUS_s_axi_U->ap_ready(ap_ready);
    hls_LK_CONTROL_BUS_s_axi_U->ap_done(ap_done);
    hls_LK_CONTROL_BUS_s_axi_U->ap_idle(ap_idle);
    hls_LK_CONTROL_BUS_s_axi_U->ap_return(hls_ComputeVectors_U0_ap_return);
    hls_LK_CONTROL_BUS_s_axi_U->height(height);
    hls_LK_CONTROL_BUS_s_axi_U->width(width);
    hls_twoIsotropicFilt_U0 = new hls_twoIsotropicFilt("hls_twoIsotropicFilt_U0");
    hls_twoIsotropicFilt_U0->ap_clk(ap_clk);
    hls_twoIsotropicFilt_U0->ap_rst(ap_rst_n_inv);
    hls_twoIsotropicFilt_U0->ap_start(hls_twoIsotropicFilt_U0_ap_start);
    hls_twoIsotropicFilt_U0->start_full_n(start_for_hls_SpatialTemporalD_U0_full_n);
    hls_twoIsotropicFilt_U0->ap_done(hls_twoIsotropicFilt_U0_ap_done);
    hls_twoIsotropicFilt_U0->ap_continue(hls_twoIsotropicFilt_U0_ap_continue);
    hls_twoIsotropicFilt_U0->ap_idle(hls_twoIsotropicFilt_U0_ap_idle);
    hls_twoIsotropicFilt_U0->ap_ready(hls_twoIsotropicFilt_U0_ap_ready);
    hls_twoIsotropicFilt_U0->start_out(hls_twoIsotropicFilt_U0_start_out);
    hls_twoIsotropicFilt_U0->start_write(hls_twoIsotropicFilt_U0_start_write);
    hls_twoIsotropicFilt_U0->inp1_img_TDATA(inp1_img_TDATA);
    hls_twoIsotropicFilt_U0->inp1_img_TVALID(inp1_img_TVALID);
    hls_twoIsotropicFilt_U0->inp1_img_TREADY(hls_twoIsotropicFilt_U0_inp1_img_TREADY);
    hls_twoIsotropicFilt_U0->inp1_img_TLAST(inp1_img_TLAST);
    hls_twoIsotropicFilt_U0->inp2_img_TDATA(inp2_img_TDATA);
    hls_twoIsotropicFilt_U0->inp2_img_TVALID(inp2_img_TVALID);
    hls_twoIsotropicFilt_U0->inp2_img_TREADY(hls_twoIsotropicFilt_U0_inp2_img_TREADY);
    hls_twoIsotropicFilt_U0->inp2_img_TLAST(inp2_img_TLAST);
    hls_twoIsotropicFilt_U0->out1_img_V_din(hls_twoIsotropicFilt_U0_out1_img_V_din);
    hls_twoIsotropicFilt_U0->out1_img_V_full_n(flt1_img_channel_full_n);
    hls_twoIsotropicFilt_U0->out1_img_V_write(hls_twoIsotropicFilt_U0_out1_img_V_write);
    hls_twoIsotropicFilt_U0->out2_img_V_din(hls_twoIsotropicFilt_U0_out2_img_V_din);
    hls_twoIsotropicFilt_U0->out2_img_V_full_n(flt2_img_channel_full_n);
    hls_twoIsotropicFilt_U0->out2_img_V_write(hls_twoIsotropicFilt_U0_out2_img_V_write);
    hls_twoIsotropicFilt_U0->height(height);
    hls_twoIsotropicFilt_U0->width(width);
    hls_twoIsotropicFilt_U0->height_out_din(hls_twoIsotropicFilt_U0_height_out_din);
    hls_twoIsotropicFilt_U0->height_out_full_n(height_c_full_n);
    hls_twoIsotropicFilt_U0->height_out_write(hls_twoIsotropicFilt_U0_height_out_write);
    hls_twoIsotropicFilt_U0->width_out_din(hls_twoIsotropicFilt_U0_width_out_din);
    hls_twoIsotropicFilt_U0->width_out_full_n(width_c_full_n);
    hls_twoIsotropicFilt_U0->width_out_write(hls_twoIsotropicFilt_U0_width_out_write);
    hls_SpatialTemporalD_U0 = new hls_SpatialTemporalD("hls_SpatialTemporalD_U0");
    hls_SpatialTemporalD_U0->ap_clk(ap_clk);
    hls_SpatialTemporalD_U0->ap_rst(ap_rst_n_inv);
    hls_SpatialTemporalD_U0->ap_start(hls_SpatialTemporalD_U0_ap_start);
    hls_SpatialTemporalD_U0->start_full_n(start_for_hls_ComputeIntegrals_U0_full_n);
    hls_SpatialTemporalD_U0->ap_done(hls_SpatialTemporalD_U0_ap_done);
    hls_SpatialTemporalD_U0->ap_continue(hls_SpatialTemporalD_U0_ap_continue);
    hls_SpatialTemporalD_U0->ap_idle(hls_SpatialTemporalD_U0_ap_idle);
    hls_SpatialTemporalD_U0->ap_ready(hls_SpatialTemporalD_U0_ap_ready);
    hls_SpatialTemporalD_U0->start_out(hls_SpatialTemporalD_U0_start_out);
    hls_SpatialTemporalD_U0->start_write(hls_SpatialTemporalD_U0_start_write);
    hls_SpatialTemporalD_U0->inp1_img_V_dout(flt1_img_channel_dout);
    hls_SpatialTemporalD_U0->inp1_img_V_empty_n(flt1_img_channel_empty_n);
    hls_SpatialTemporalD_U0->inp1_img_V_read(hls_SpatialTemporalD_U0_inp1_img_V_read);
    hls_SpatialTemporalD_U0->inp2_img_V_dout(flt2_img_channel_dout);
    hls_SpatialTemporalD_U0->inp2_img_V_empty_n(flt2_img_channel_empty_n);
    hls_SpatialTemporalD_U0->inp2_img_V_read(hls_SpatialTemporalD_U0_inp2_img_V_read);
    hls_SpatialTemporalD_U0->out_Ix_img_V_din(hls_SpatialTemporalD_U0_out_Ix_img_V_din);
    hls_SpatialTemporalD_U0->out_Ix_img_V_full_n(Dx1_img_channel_full_n);
    hls_SpatialTemporalD_U0->out_Ix_img_V_write(hls_SpatialTemporalD_U0_out_Ix_img_V_write);
    hls_SpatialTemporalD_U0->out_Iy_img_V_din(hls_SpatialTemporalD_U0_out_Iy_img_V_din);
    hls_SpatialTemporalD_U0->out_Iy_img_V_full_n(Dy1_img_channel_full_n);
    hls_SpatialTemporalD_U0->out_Iy_img_V_write(hls_SpatialTemporalD_U0_out_Iy_img_V_write);
    hls_SpatialTemporalD_U0->out_It_img_V_din(hls_SpatialTemporalD_U0_out_It_img_V_din);
    hls_SpatialTemporalD_U0->out_It_img_V_full_n(Dt_img_channel_full_n);
    hls_SpatialTemporalD_U0->out_It_img_V_write(hls_SpatialTemporalD_U0_out_It_img_V_write);
    hls_SpatialTemporalD_U0->height_dout(height_c_dout);
    hls_SpatialTemporalD_U0->height_empty_n(height_c_empty_n);
    hls_SpatialTemporalD_U0->height_read(hls_SpatialTemporalD_U0_height_read);
    hls_SpatialTemporalD_U0->width_dout(width_c_dout);
    hls_SpatialTemporalD_U0->width_empty_n(width_c_empty_n);
    hls_SpatialTemporalD_U0->width_read(hls_SpatialTemporalD_U0_width_read);
    hls_SpatialTemporalD_U0->height_out_din(hls_SpatialTemporalD_U0_height_out_din);
    hls_SpatialTemporalD_U0->height_out_full_n(height_c9_full_n);
    hls_SpatialTemporalD_U0->height_out_write(hls_SpatialTemporalD_U0_height_out_write);
    hls_SpatialTemporalD_U0->width_out_din(hls_SpatialTemporalD_U0_width_out_din);
    hls_SpatialTemporalD_U0->width_out_full_n(width_c10_full_n);
    hls_SpatialTemporalD_U0->width_out_write(hls_SpatialTemporalD_U0_width_out_write);
    hls_ComputeIntegrals_U0 = new hls_ComputeIntegrals("hls_ComputeIntegrals_U0");
    hls_ComputeIntegrals_U0->ap_clk(ap_clk);
    hls_ComputeIntegrals_U0->ap_rst(ap_rst_n_inv);
    hls_ComputeIntegrals_U0->ap_start(hls_ComputeIntegrals_U0_ap_start);
    hls_ComputeIntegrals_U0->start_full_n(start_for_hls_ComputeVectors_U0_full_n);
    hls_ComputeIntegrals_U0->ap_done(hls_ComputeIntegrals_U0_ap_done);
    hls_ComputeIntegrals_U0->ap_continue(hls_ComputeIntegrals_U0_ap_continue);
    hls_ComputeIntegrals_U0->ap_idle(hls_ComputeIntegrals_U0_ap_idle);
    hls_ComputeIntegrals_U0->ap_ready(hls_ComputeIntegrals_U0_ap_ready);
    hls_ComputeIntegrals_U0->start_out(hls_ComputeIntegrals_U0_start_out);
    hls_ComputeIntegrals_U0->start_write(hls_ComputeIntegrals_U0_start_write);
    hls_ComputeIntegrals_U0->Ix_img_V_dout(Dx1_img_channel_dout);
    hls_ComputeIntegrals_U0->Ix_img_V_empty_n(Dx1_img_channel_empty_n);
    hls_ComputeIntegrals_U0->Ix_img_V_read(hls_ComputeIntegrals_U0_Ix_img_V_read);
    hls_ComputeIntegrals_U0->Iy_img_V_dout(Dy1_img_channel_dout);
    hls_ComputeIntegrals_U0->Iy_img_V_empty_n(Dy1_img_channel_empty_n);
    hls_ComputeIntegrals_U0->Iy_img_V_read(hls_ComputeIntegrals_U0_Iy_img_V_read);
    hls_ComputeIntegrals_U0->It_img_V_dout(Dt_img_channel_dout);
    hls_ComputeIntegrals_U0->It_img_V_empty_n(Dt_img_channel_empty_n);
    hls_ComputeIntegrals_U0->It_img_V_read(hls_ComputeIntegrals_U0_It_img_V_read);
    hls_ComputeIntegrals_U0->A11_img_V_din(hls_ComputeIntegrals_U0_A11_img_V_din);
    hls_ComputeIntegrals_U0->A11_img_V_full_n(A11_img_channel_full_n);
    hls_ComputeIntegrals_U0->A11_img_V_write(hls_ComputeIntegrals_U0_A11_img_V_write);
    hls_ComputeIntegrals_U0->A12_img_V_din(hls_ComputeIntegrals_U0_A12_img_V_din);
    hls_ComputeIntegrals_U0->A12_img_V_full_n(A12_img_channel_full_n);
    hls_ComputeIntegrals_U0->A12_img_V_write(hls_ComputeIntegrals_U0_A12_img_V_write);
    hls_ComputeIntegrals_U0->A22_img_V_din(hls_ComputeIntegrals_U0_A22_img_V_din);
    hls_ComputeIntegrals_U0->A22_img_V_full_n(A22_img_channel_full_n);
    hls_ComputeIntegrals_U0->A22_img_V_write(hls_ComputeIntegrals_U0_A22_img_V_write);
    hls_ComputeIntegrals_U0->B1_img_V_din(hls_ComputeIntegrals_U0_B1_img_V_din);
    hls_ComputeIntegrals_U0->B1_img_V_full_n(B1_img_channel_full_n);
    hls_ComputeIntegrals_U0->B1_img_V_write(hls_ComputeIntegrals_U0_B1_img_V_write);
    hls_ComputeIntegrals_U0->B2_img_V_din(hls_ComputeIntegrals_U0_B2_img_V_din);
    hls_ComputeIntegrals_U0->B2_img_V_full_n(B2_img_channel_full_n);
    hls_ComputeIntegrals_U0->B2_img_V_write(hls_ComputeIntegrals_U0_B2_img_V_write);
    hls_ComputeIntegrals_U0->height_dout(height_c9_dout);
    hls_ComputeIntegrals_U0->height_empty_n(height_c9_empty_n);
    hls_ComputeIntegrals_U0->height_read(hls_ComputeIntegrals_U0_height_read);
    hls_ComputeIntegrals_U0->width_dout(width_c10_dout);
    hls_ComputeIntegrals_U0->width_empty_n(width_c10_empty_n);
    hls_ComputeIntegrals_U0->width_read(hls_ComputeIntegrals_U0_width_read);
    hls_ComputeIntegrals_U0->height_out_din(hls_ComputeIntegrals_U0_height_out_din);
    hls_ComputeIntegrals_U0->height_out_full_n(height_c11_full_n);
    hls_ComputeIntegrals_U0->height_out_write(hls_ComputeIntegrals_U0_height_out_write);
    hls_ComputeIntegrals_U0->width_out_din(hls_ComputeIntegrals_U0_width_out_din);
    hls_ComputeIntegrals_U0->width_out_full_n(width_c12_full_n);
    hls_ComputeIntegrals_U0->width_out_write(hls_ComputeIntegrals_U0_width_out_write);
    hls_ComputeVectors_U0 = new hls_ComputeVectors("hls_ComputeVectors_U0");
    hls_ComputeVectors_U0->ap_clk(ap_clk);
    hls_ComputeVectors_U0->ap_rst(ap_rst_n_inv);
    hls_ComputeVectors_U0->ap_start(hls_ComputeVectors_U0_ap_start);
    hls_ComputeVectors_U0->ap_done(hls_ComputeVectors_U0_ap_done);
    hls_ComputeVectors_U0->ap_continue(hls_ComputeVectors_U0_ap_continue);
    hls_ComputeVectors_U0->ap_idle(hls_ComputeVectors_U0_ap_idle);
    hls_ComputeVectors_U0->ap_ready(hls_ComputeVectors_U0_ap_ready);
    hls_ComputeVectors_U0->A11_img_V_dout(A11_img_channel_dout);
    hls_ComputeVectors_U0->A11_img_V_empty_n(A11_img_channel_empty_n);
    hls_ComputeVectors_U0->A11_img_V_read(hls_ComputeVectors_U0_A11_img_V_read);
    hls_ComputeVectors_U0->A12_img_V_dout(A12_img_channel_dout);
    hls_ComputeVectors_U0->A12_img_V_empty_n(A12_img_channel_empty_n);
    hls_ComputeVectors_U0->A12_img_V_read(hls_ComputeVectors_U0_A12_img_V_read);
    hls_ComputeVectors_U0->A22_img_V_dout(A22_img_channel_dout);
    hls_ComputeVectors_U0->A22_img_V_empty_n(A22_img_channel_empty_n);
    hls_ComputeVectors_U0->A22_img_V_read(hls_ComputeVectors_U0_A22_img_V_read);
    hls_ComputeVectors_U0->B1_img_V_dout(B1_img_channel_dout);
    hls_ComputeVectors_U0->B1_img_V_empty_n(B1_img_channel_empty_n);
    hls_ComputeVectors_U0->B1_img_V_read(hls_ComputeVectors_U0_B1_img_V_read);
    hls_ComputeVectors_U0->B2_img_V_dout(B2_img_channel_dout);
    hls_ComputeVectors_U0->B2_img_V_empty_n(B2_img_channel_empty_n);
    hls_ComputeVectors_U0->B2_img_V_read(hls_ComputeVectors_U0_B2_img_V_read);
    hls_ComputeVectors_U0->vx_img_TDATA(hls_ComputeVectors_U0_vx_img_TDATA);
    hls_ComputeVectors_U0->vx_img_TVALID(hls_ComputeVectors_U0_vx_img_TVALID);
    hls_ComputeVectors_U0->vx_img_TREADY(vx_img_TREADY);
    hls_ComputeVectors_U0->vx_img_TLAST(hls_ComputeVectors_U0_vx_img_TLAST);
    hls_ComputeVectors_U0->vy_img_TDATA(hls_ComputeVectors_U0_vy_img_TDATA);
    hls_ComputeVectors_U0->vy_img_TVALID(hls_ComputeVectors_U0_vy_img_TVALID);
    hls_ComputeVectors_U0->vy_img_TREADY(vy_img_TREADY);
    hls_ComputeVectors_U0->vy_img_TLAST(hls_ComputeVectors_U0_vy_img_TLAST);
    hls_ComputeVectors_U0->height_dout(height_c11_dout);
    hls_ComputeVectors_U0->height_empty_n(height_c11_empty_n);
    hls_ComputeVectors_U0->height_read(hls_ComputeVectors_U0_height_read);
    hls_ComputeVectors_U0->width_dout(width_c12_dout);
    hls_ComputeVectors_U0->width_empty_n(width_c12_empty_n);
    hls_ComputeVectors_U0->width_read(hls_ComputeVectors_U0_width_read);
    hls_ComputeVectors_U0->ap_return(hls_ComputeVectors_U0_ap_return);
    flt1_img_channel_U = new fifo_w12_d10_A("flt1_img_channel_U");
    flt1_img_channel_U->clk(ap_clk);
    flt1_img_channel_U->reset(ap_rst_n_inv);
    flt1_img_channel_U->if_read_ce(ap_var_for_const0);
    flt1_img_channel_U->if_write_ce(ap_var_for_const0);
    flt1_img_channel_U->if_din(hls_twoIsotropicFilt_U0_out1_img_V_din);
    flt1_img_channel_U->if_full_n(flt1_img_channel_full_n);
    flt1_img_channel_U->if_write(hls_twoIsotropicFilt_U0_out1_img_V_write);
    flt1_img_channel_U->if_dout(flt1_img_channel_dout);
    flt1_img_channel_U->if_empty_n(flt1_img_channel_empty_n);
    flt1_img_channel_U->if_read(hls_SpatialTemporalD_U0_inp1_img_V_read);
    flt2_img_channel_U = new fifo_w12_d10_A("flt2_img_channel_U");
    flt2_img_channel_U->clk(ap_clk);
    flt2_img_channel_U->reset(ap_rst_n_inv);
    flt2_img_channel_U->if_read_ce(ap_var_for_const0);
    flt2_img_channel_U->if_write_ce(ap_var_for_const0);
    flt2_img_channel_U->if_din(hls_twoIsotropicFilt_U0_out2_img_V_din);
    flt2_img_channel_U->if_full_n(flt2_img_channel_full_n);
    flt2_img_channel_U->if_write(hls_twoIsotropicFilt_U0_out2_img_V_write);
    flt2_img_channel_U->if_dout(flt2_img_channel_dout);
    flt2_img_channel_U->if_empty_n(flt2_img_channel_empty_n);
    flt2_img_channel_U->if_read(hls_SpatialTemporalD_U0_inp2_img_V_read);
    height_c_U = new fifo_w16_d2_A("height_c_U");
    height_c_U->clk(ap_clk);
    height_c_U->reset(ap_rst_n_inv);
    height_c_U->if_read_ce(ap_var_for_const0);
    height_c_U->if_write_ce(ap_var_for_const0);
    height_c_U->if_din(hls_twoIsotropicFilt_U0_height_out_din);
    height_c_U->if_full_n(height_c_full_n);
    height_c_U->if_write(hls_twoIsotropicFilt_U0_height_out_write);
    height_c_U->if_dout(height_c_dout);
    height_c_U->if_empty_n(height_c_empty_n);
    height_c_U->if_read(hls_SpatialTemporalD_U0_height_read);
    width_c_U = new fifo_w16_d2_A("width_c_U");
    width_c_U->clk(ap_clk);
    width_c_U->reset(ap_rst_n_inv);
    width_c_U->if_read_ce(ap_var_for_const0);
    width_c_U->if_write_ce(ap_var_for_const0);
    width_c_U->if_din(hls_twoIsotropicFilt_U0_width_out_din);
    width_c_U->if_full_n(width_c_full_n);
    width_c_U->if_write(hls_twoIsotropicFilt_U0_width_out_write);
    width_c_U->if_dout(width_c_dout);
    width_c_U->if_empty_n(width_c_empty_n);
    width_c_U->if_read(hls_SpatialTemporalD_U0_width_read);
    Dx1_img_channel_U = new fifo_w13_d10_A("Dx1_img_channel_U");
    Dx1_img_channel_U->clk(ap_clk);
    Dx1_img_channel_U->reset(ap_rst_n_inv);
    Dx1_img_channel_U->if_read_ce(ap_var_for_const0);
    Dx1_img_channel_U->if_write_ce(ap_var_for_const0);
    Dx1_img_channel_U->if_din(hls_SpatialTemporalD_U0_out_Ix_img_V_din);
    Dx1_img_channel_U->if_full_n(Dx1_img_channel_full_n);
    Dx1_img_channel_U->if_write(hls_SpatialTemporalD_U0_out_Ix_img_V_write);
    Dx1_img_channel_U->if_dout(Dx1_img_channel_dout);
    Dx1_img_channel_U->if_empty_n(Dx1_img_channel_empty_n);
    Dx1_img_channel_U->if_read(hls_ComputeIntegrals_U0_Ix_img_V_read);
    Dy1_img_channel_U = new fifo_w13_d10_A("Dy1_img_channel_U");
    Dy1_img_channel_U->clk(ap_clk);
    Dy1_img_channel_U->reset(ap_rst_n_inv);
    Dy1_img_channel_U->if_read_ce(ap_var_for_const0);
    Dy1_img_channel_U->if_write_ce(ap_var_for_const0);
    Dy1_img_channel_U->if_din(hls_SpatialTemporalD_U0_out_Iy_img_V_din);
    Dy1_img_channel_U->if_full_n(Dy1_img_channel_full_n);
    Dy1_img_channel_U->if_write(hls_SpatialTemporalD_U0_out_Iy_img_V_write);
    Dy1_img_channel_U->if_dout(Dy1_img_channel_dout);
    Dy1_img_channel_U->if_empty_n(Dy1_img_channel_empty_n);
    Dy1_img_channel_U->if_read(hls_ComputeIntegrals_U0_Iy_img_V_read);
    Dt_img_channel_U = new fifo_w13_d10_A("Dt_img_channel_U");
    Dt_img_channel_U->clk(ap_clk);
    Dt_img_channel_U->reset(ap_rst_n_inv);
    Dt_img_channel_U->if_read_ce(ap_var_for_const0);
    Dt_img_channel_U->if_write_ce(ap_var_for_const0);
    Dt_img_channel_U->if_din(hls_SpatialTemporalD_U0_out_It_img_V_din);
    Dt_img_channel_U->if_full_n(Dt_img_channel_full_n);
    Dt_img_channel_U->if_write(hls_SpatialTemporalD_U0_out_It_img_V_write);
    Dt_img_channel_U->if_dout(Dt_img_channel_dout);
    Dt_img_channel_U->if_empty_n(Dt_img_channel_empty_n);
    Dt_img_channel_U->if_read(hls_ComputeIntegrals_U0_It_img_V_read);
    height_c9_U = new fifo_w16_d2_A("height_c9_U");
    height_c9_U->clk(ap_clk);
    height_c9_U->reset(ap_rst_n_inv);
    height_c9_U->if_read_ce(ap_var_for_const0);
    height_c9_U->if_write_ce(ap_var_for_const0);
    height_c9_U->if_din(hls_SpatialTemporalD_U0_height_out_din);
    height_c9_U->if_full_n(height_c9_full_n);
    height_c9_U->if_write(hls_SpatialTemporalD_U0_height_out_write);
    height_c9_U->if_dout(height_c9_dout);
    height_c9_U->if_empty_n(height_c9_empty_n);
    height_c9_U->if_read(hls_ComputeIntegrals_U0_height_read);
    width_c10_U = new fifo_w16_d2_A("width_c10_U");
    width_c10_U->clk(ap_clk);
    width_c10_U->reset(ap_rst_n_inv);
    width_c10_U->if_read_ce(ap_var_for_const0);
    width_c10_U->if_write_ce(ap_var_for_const0);
    width_c10_U->if_din(hls_SpatialTemporalD_U0_width_out_din);
    width_c10_U->if_full_n(width_c10_full_n);
    width_c10_U->if_write(hls_SpatialTemporalD_U0_width_out_write);
    width_c10_U->if_dout(width_c10_dout);
    width_c10_U->if_empty_n(width_c10_empty_n);
    width_c10_U->if_read(hls_ComputeIntegrals_U0_width_read);
    A11_img_channel_U = new fifo_w34_d10_A("A11_img_channel_U");
    A11_img_channel_U->clk(ap_clk);
    A11_img_channel_U->reset(ap_rst_n_inv);
    A11_img_channel_U->if_read_ce(ap_var_for_const0);
    A11_img_channel_U->if_write_ce(ap_var_for_const0);
    A11_img_channel_U->if_din(hls_ComputeIntegrals_U0_A11_img_V_din);
    A11_img_channel_U->if_full_n(A11_img_channel_full_n);
    A11_img_channel_U->if_write(hls_ComputeIntegrals_U0_A11_img_V_write);
    A11_img_channel_U->if_dout(A11_img_channel_dout);
    A11_img_channel_U->if_empty_n(A11_img_channel_empty_n);
    A11_img_channel_U->if_read(hls_ComputeVectors_U0_A11_img_V_read);
    A12_img_channel_U = new fifo_w34_d10_A("A12_img_channel_U");
    A12_img_channel_U->clk(ap_clk);
    A12_img_channel_U->reset(ap_rst_n_inv);
    A12_img_channel_U->if_read_ce(ap_var_for_const0);
    A12_img_channel_U->if_write_ce(ap_var_for_const0);
    A12_img_channel_U->if_din(hls_ComputeIntegrals_U0_A12_img_V_din);
    A12_img_channel_U->if_full_n(A12_img_channel_full_n);
    A12_img_channel_U->if_write(hls_ComputeIntegrals_U0_A12_img_V_write);
    A12_img_channel_U->if_dout(A12_img_channel_dout);
    A12_img_channel_U->if_empty_n(A12_img_channel_empty_n);
    A12_img_channel_U->if_read(hls_ComputeVectors_U0_A12_img_V_read);
    A22_img_channel_U = new fifo_w34_d10_A("A22_img_channel_U");
    A22_img_channel_U->clk(ap_clk);
    A22_img_channel_U->reset(ap_rst_n_inv);
    A22_img_channel_U->if_read_ce(ap_var_for_const0);
    A22_img_channel_U->if_write_ce(ap_var_for_const0);
    A22_img_channel_U->if_din(hls_ComputeIntegrals_U0_A22_img_V_din);
    A22_img_channel_U->if_full_n(A22_img_channel_full_n);
    A22_img_channel_U->if_write(hls_ComputeIntegrals_U0_A22_img_V_write);
    A22_img_channel_U->if_dout(A22_img_channel_dout);
    A22_img_channel_U->if_empty_n(A22_img_channel_empty_n);
    A22_img_channel_U->if_read(hls_ComputeVectors_U0_A22_img_V_read);
    B1_img_channel_U = new fifo_w34_d10_A("B1_img_channel_U");
    B1_img_channel_U->clk(ap_clk);
    B1_img_channel_U->reset(ap_rst_n_inv);
    B1_img_channel_U->if_read_ce(ap_var_for_const0);
    B1_img_channel_U->if_write_ce(ap_var_for_const0);
    B1_img_channel_U->if_din(hls_ComputeIntegrals_U0_B1_img_V_din);
    B1_img_channel_U->if_full_n(B1_img_channel_full_n);
    B1_img_channel_U->if_write(hls_ComputeIntegrals_U0_B1_img_V_write);
    B1_img_channel_U->if_dout(B1_img_channel_dout);
    B1_img_channel_U->if_empty_n(B1_img_channel_empty_n);
    B1_img_channel_U->if_read(hls_ComputeVectors_U0_B1_img_V_read);
    B2_img_channel_U = new fifo_w34_d10_A("B2_img_channel_U");
    B2_img_channel_U->clk(ap_clk);
    B2_img_channel_U->reset(ap_rst_n_inv);
    B2_img_channel_U->if_read_ce(ap_var_for_const0);
    B2_img_channel_U->if_write_ce(ap_var_for_const0);
    B2_img_channel_U->if_din(hls_ComputeIntegrals_U0_B2_img_V_din);
    B2_img_channel_U->if_full_n(B2_img_channel_full_n);
    B2_img_channel_U->if_write(hls_ComputeIntegrals_U0_B2_img_V_write);
    B2_img_channel_U->if_dout(B2_img_channel_dout);
    B2_img_channel_U->if_empty_n(B2_img_channel_empty_n);
    B2_img_channel_U->if_read(hls_ComputeVectors_U0_B2_img_V_read);
    height_c11_U = new fifo_w16_d2_A("height_c11_U");
    height_c11_U->clk(ap_clk);
    height_c11_U->reset(ap_rst_n_inv);
    height_c11_U->if_read_ce(ap_var_for_const0);
    height_c11_U->if_write_ce(ap_var_for_const0);
    height_c11_U->if_din(hls_ComputeIntegrals_U0_height_out_din);
    height_c11_U->if_full_n(height_c11_full_n);
    height_c11_U->if_write(hls_ComputeIntegrals_U0_height_out_write);
    height_c11_U->if_dout(height_c11_dout);
    height_c11_U->if_empty_n(height_c11_empty_n);
    height_c11_U->if_read(hls_ComputeVectors_U0_height_read);
    width_c12_U = new fifo_w16_d2_A("width_c12_U");
    width_c12_U->clk(ap_clk);
    width_c12_U->reset(ap_rst_n_inv);
    width_c12_U->if_read_ce(ap_var_for_const0);
    width_c12_U->if_write_ce(ap_var_for_const0);
    width_c12_U->if_din(hls_ComputeIntegrals_U0_width_out_din);
    width_c12_U->if_full_n(width_c12_full_n);
    width_c12_U->if_write(hls_ComputeIntegrals_U0_width_out_write);
    width_c12_U->if_dout(width_c12_dout);
    width_c12_U->if_empty_n(width_c12_empty_n);
    width_c12_U->if_read(hls_ComputeVectors_U0_width_read);
    start_for_hls_SpatialTemporalD_U0_U = new start_for_hls_SpatialTemporalD_U0("start_for_hls_SpatialTemporalD_U0_U");
    start_for_hls_SpatialTemporalD_U0_U->clk(ap_clk);
    start_for_hls_SpatialTemporalD_U0_U->reset(ap_rst_n_inv);
    start_for_hls_SpatialTemporalD_U0_U->if_read_ce(ap_var_for_const0);
    start_for_hls_SpatialTemporalD_U0_U->if_write_ce(ap_var_for_const0);
    start_for_hls_SpatialTemporalD_U0_U->if_din(start_for_hls_SpatialTemporalD_U0_din);
    start_for_hls_SpatialTemporalD_U0_U->if_full_n(start_for_hls_SpatialTemporalD_U0_full_n);
    start_for_hls_SpatialTemporalD_U0_U->if_write(hls_twoIsotropicFilt_U0_start_write);
    start_for_hls_SpatialTemporalD_U0_U->if_dout(start_for_hls_SpatialTemporalD_U0_dout);
    start_for_hls_SpatialTemporalD_U0_U->if_empty_n(start_for_hls_SpatialTemporalD_U0_empty_n);
    start_for_hls_SpatialTemporalD_U0_U->if_read(hls_SpatialTemporalD_U0_ap_ready);
    start_for_hls_ComputeIntegrals_U0_U = new start_for_hls_ComputeIntegrals_U0("start_for_hls_ComputeIntegrals_U0_U");
    start_for_hls_ComputeIntegrals_U0_U->clk(ap_clk);
    start_for_hls_ComputeIntegrals_U0_U->reset(ap_rst_n_inv);
    start_for_hls_ComputeIntegrals_U0_U->if_read_ce(ap_var_for_const0);
    start_for_hls_ComputeIntegrals_U0_U->if_write_ce(ap_var_for_const0);
    start_for_hls_ComputeIntegrals_U0_U->if_din(start_for_hls_ComputeIntegrals_U0_din);
    start_for_hls_ComputeIntegrals_U0_U->if_full_n(start_for_hls_ComputeIntegrals_U0_full_n);
    start_for_hls_ComputeIntegrals_U0_U->if_write(hls_SpatialTemporalD_U0_start_write);
    start_for_hls_ComputeIntegrals_U0_U->if_dout(start_for_hls_ComputeIntegrals_U0_dout);
    start_for_hls_ComputeIntegrals_U0_U->if_empty_n(start_for_hls_ComputeIntegrals_U0_empty_n);
    start_for_hls_ComputeIntegrals_U0_U->if_read(hls_ComputeIntegrals_U0_ap_ready);
    start_for_hls_ComputeVectors_U0_U = new start_for_hls_ComputeVectors_U0("start_for_hls_ComputeVectors_U0_U");
    start_for_hls_ComputeVectors_U0_U->clk(ap_clk);
    start_for_hls_ComputeVectors_U0_U->reset(ap_rst_n_inv);
    start_for_hls_ComputeVectors_U0_U->if_read_ce(ap_var_for_const0);
    start_for_hls_ComputeVectors_U0_U->if_write_ce(ap_var_for_const0);
    start_for_hls_ComputeVectors_U0_U->if_din(start_for_hls_ComputeVectors_U0_din);
    start_for_hls_ComputeVectors_U0_U->if_full_n(start_for_hls_ComputeVectors_U0_full_n);
    start_for_hls_ComputeVectors_U0_U->if_write(hls_ComputeIntegrals_U0_start_write);
    start_for_hls_ComputeVectors_U0_U->if_dout(start_for_hls_ComputeVectors_U0_dout);
    start_for_hls_ComputeVectors_U0_U->if_empty_n(start_for_hls_ComputeVectors_U0_empty_n);
    start_for_hls_ComputeVectors_U0_U->if_read(hls_ComputeVectors_U0_ap_ready);

    SC_METHOD(thread_ap_done);
    sensitive << ( hls_ComputeVectors_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( hls_twoIsotropicFilt_U0_ap_idle );
    sensitive << ( hls_SpatialTemporalD_U0_ap_idle );
    sensitive << ( hls_ComputeIntegrals_U0_ap_idle );
    sensitive << ( hls_ComputeVectors_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( hls_twoIsotropicFilt_U0_ap_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( hls_ComputeVectors_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( hls_twoIsotropicFilt_U0_ap_ready );

    SC_METHOD(thread_hls_ComputeIntegrals_U0_ap_continue);

    SC_METHOD(thread_hls_ComputeIntegrals_U0_ap_start);
    sensitive << ( start_for_hls_ComputeIntegrals_U0_empty_n );

    SC_METHOD(thread_hls_ComputeVectors_U0_ap_continue);

    SC_METHOD(thread_hls_ComputeVectors_U0_ap_start);
    sensitive << ( start_for_hls_ComputeVectors_U0_empty_n );

    SC_METHOD(thread_hls_ComputeVectors_U0_start_full_n);

    SC_METHOD(thread_hls_ComputeVectors_U0_start_write);

    SC_METHOD(thread_hls_SpatialTemporalD_U0_ap_continue);

    SC_METHOD(thread_hls_SpatialTemporalD_U0_ap_start);
    sensitive << ( start_for_hls_SpatialTemporalD_U0_empty_n );

    SC_METHOD(thread_hls_twoIsotropicFilt_U0_ap_continue);

    SC_METHOD(thread_hls_twoIsotropicFilt_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_inp1_img_TREADY);
    sensitive << ( hls_twoIsotropicFilt_U0_inp1_img_TREADY );

    SC_METHOD(thread_inp2_img_TREADY);
    sensitive << ( hls_twoIsotropicFilt_U0_inp2_img_TREADY );

    SC_METHOD(thread_start_for_hls_ComputeIntegrals_U0_din);

    SC_METHOD(thread_start_for_hls_ComputeVectors_U0_din);

    SC_METHOD(thread_start_for_hls_SpatialTemporalD_U0_din);

    SC_METHOD(thread_vx_img_TDATA);
    sensitive << ( hls_ComputeVectors_U0_vx_img_TDATA );

    SC_METHOD(thread_vx_img_TLAST);
    sensitive << ( hls_ComputeVectors_U0_vx_img_TLAST );

    SC_METHOD(thread_vx_img_TVALID);
    sensitive << ( hls_ComputeVectors_U0_vx_img_TVALID );

    SC_METHOD(thread_vy_img_TDATA);
    sensitive << ( hls_ComputeVectors_U0_vy_img_TDATA );

    SC_METHOD(thread_vy_img_TLAST);
    sensitive << ( hls_ComputeVectors_U0_vy_img_TLAST );

    SC_METHOD(thread_vy_img_TVALID);
    sensitive << ( hls_ComputeVectors_U0_vy_img_TVALID );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hls_LK_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWVALID, "(port)s_axi_CONTROL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWREADY, "(port)s_axi_CONTROL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWADDR, "(port)s_axi_CONTROL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WVALID, "(port)s_axi_CONTROL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WREADY, "(port)s_axi_CONTROL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WDATA, "(port)s_axi_CONTROL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WSTRB, "(port)s_axi_CONTROL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARVALID, "(port)s_axi_CONTROL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARREADY, "(port)s_axi_CONTROL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARADDR, "(port)s_axi_CONTROL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RVALID, "(port)s_axi_CONTROL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RREADY, "(port)s_axi_CONTROL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RDATA, "(port)s_axi_CONTROL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RRESP, "(port)s_axi_CONTROL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BVALID, "(port)s_axi_CONTROL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BREADY, "(port)s_axi_CONTROL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BRESP, "(port)s_axi_CONTROL_BUS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
    sc_trace(mVcdFile, inp1_img_TDATA, "(port)inp1_img_TDATA");
    sc_trace(mVcdFile, inp1_img_TLAST, "(port)inp1_img_TLAST");
    sc_trace(mVcdFile, inp2_img_TDATA, "(port)inp2_img_TDATA");
    sc_trace(mVcdFile, inp2_img_TLAST, "(port)inp2_img_TLAST");
    sc_trace(mVcdFile, vx_img_TDATA, "(port)vx_img_TDATA");
    sc_trace(mVcdFile, vx_img_TLAST, "(port)vx_img_TLAST");
    sc_trace(mVcdFile, vy_img_TDATA, "(port)vy_img_TDATA");
    sc_trace(mVcdFile, vy_img_TLAST, "(port)vy_img_TLAST");
    sc_trace(mVcdFile, inp1_img_TVALID, "(port)inp1_img_TVALID");
    sc_trace(mVcdFile, inp1_img_TREADY, "(port)inp1_img_TREADY");
    sc_trace(mVcdFile, inp2_img_TVALID, "(port)inp2_img_TVALID");
    sc_trace(mVcdFile, inp2_img_TREADY, "(port)inp2_img_TREADY");
    sc_trace(mVcdFile, vx_img_TVALID, "(port)vx_img_TVALID");
    sc_trace(mVcdFile, vx_img_TREADY, "(port)vx_img_TREADY");
    sc_trace(mVcdFile, vy_img_TVALID, "(port)vy_img_TVALID");
    sc_trace(mVcdFile, vy_img_TREADY, "(port)vy_img_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, height, "height");
    sc_trace(mVcdFile, width, "width");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_ap_start, "hls_twoIsotropicFilt_U0_ap_start");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_ap_done, "hls_twoIsotropicFilt_U0_ap_done");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_ap_continue, "hls_twoIsotropicFilt_U0_ap_continue");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_ap_idle, "hls_twoIsotropicFilt_U0_ap_idle");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_ap_ready, "hls_twoIsotropicFilt_U0_ap_ready");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_start_out, "hls_twoIsotropicFilt_U0_start_out");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_start_write, "hls_twoIsotropicFilt_U0_start_write");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_inp1_img_TREADY, "hls_twoIsotropicFilt_U0_inp1_img_TREADY");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_inp2_img_TREADY, "hls_twoIsotropicFilt_U0_inp2_img_TREADY");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_out1_img_V_din, "hls_twoIsotropicFilt_U0_out1_img_V_din");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_out1_img_V_write, "hls_twoIsotropicFilt_U0_out1_img_V_write");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_out2_img_V_din, "hls_twoIsotropicFilt_U0_out2_img_V_din");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_out2_img_V_write, "hls_twoIsotropicFilt_U0_out2_img_V_write");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_height_out_din, "hls_twoIsotropicFilt_U0_height_out_din");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_height_out_write, "hls_twoIsotropicFilt_U0_height_out_write");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_width_out_din, "hls_twoIsotropicFilt_U0_width_out_din");
    sc_trace(mVcdFile, hls_twoIsotropicFilt_U0_width_out_write, "hls_twoIsotropicFilt_U0_width_out_write");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_ap_start, "hls_SpatialTemporalD_U0_ap_start");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_ap_done, "hls_SpatialTemporalD_U0_ap_done");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_ap_continue, "hls_SpatialTemporalD_U0_ap_continue");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_ap_idle, "hls_SpatialTemporalD_U0_ap_idle");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_ap_ready, "hls_SpatialTemporalD_U0_ap_ready");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_start_out, "hls_SpatialTemporalD_U0_start_out");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_start_write, "hls_SpatialTemporalD_U0_start_write");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_inp1_img_V_read, "hls_SpatialTemporalD_U0_inp1_img_V_read");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_inp2_img_V_read, "hls_SpatialTemporalD_U0_inp2_img_V_read");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_out_Ix_img_V_din, "hls_SpatialTemporalD_U0_out_Ix_img_V_din");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_out_Ix_img_V_write, "hls_SpatialTemporalD_U0_out_Ix_img_V_write");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_out_Iy_img_V_din, "hls_SpatialTemporalD_U0_out_Iy_img_V_din");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_out_Iy_img_V_write, "hls_SpatialTemporalD_U0_out_Iy_img_V_write");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_out_It_img_V_din, "hls_SpatialTemporalD_U0_out_It_img_V_din");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_out_It_img_V_write, "hls_SpatialTemporalD_U0_out_It_img_V_write");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_height_read, "hls_SpatialTemporalD_U0_height_read");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_width_read, "hls_SpatialTemporalD_U0_width_read");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_height_out_din, "hls_SpatialTemporalD_U0_height_out_din");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_height_out_write, "hls_SpatialTemporalD_U0_height_out_write");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_width_out_din, "hls_SpatialTemporalD_U0_width_out_din");
    sc_trace(mVcdFile, hls_SpatialTemporalD_U0_width_out_write, "hls_SpatialTemporalD_U0_width_out_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_ap_start, "hls_ComputeIntegrals_U0_ap_start");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_ap_done, "hls_ComputeIntegrals_U0_ap_done");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_ap_continue, "hls_ComputeIntegrals_U0_ap_continue");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_ap_idle, "hls_ComputeIntegrals_U0_ap_idle");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_ap_ready, "hls_ComputeIntegrals_U0_ap_ready");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_start_out, "hls_ComputeIntegrals_U0_start_out");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_start_write, "hls_ComputeIntegrals_U0_start_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_Ix_img_V_read, "hls_ComputeIntegrals_U0_Ix_img_V_read");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_Iy_img_V_read, "hls_ComputeIntegrals_U0_Iy_img_V_read");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_It_img_V_read, "hls_ComputeIntegrals_U0_It_img_V_read");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_A11_img_V_din, "hls_ComputeIntegrals_U0_A11_img_V_din");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_A11_img_V_write, "hls_ComputeIntegrals_U0_A11_img_V_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_A12_img_V_din, "hls_ComputeIntegrals_U0_A12_img_V_din");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_A12_img_V_write, "hls_ComputeIntegrals_U0_A12_img_V_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_A22_img_V_din, "hls_ComputeIntegrals_U0_A22_img_V_din");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_A22_img_V_write, "hls_ComputeIntegrals_U0_A22_img_V_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_B1_img_V_din, "hls_ComputeIntegrals_U0_B1_img_V_din");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_B1_img_V_write, "hls_ComputeIntegrals_U0_B1_img_V_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_B2_img_V_din, "hls_ComputeIntegrals_U0_B2_img_V_din");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_B2_img_V_write, "hls_ComputeIntegrals_U0_B2_img_V_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_height_read, "hls_ComputeIntegrals_U0_height_read");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_width_read, "hls_ComputeIntegrals_U0_width_read");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_height_out_din, "hls_ComputeIntegrals_U0_height_out_din");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_height_out_write, "hls_ComputeIntegrals_U0_height_out_write");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_width_out_din, "hls_ComputeIntegrals_U0_width_out_din");
    sc_trace(mVcdFile, hls_ComputeIntegrals_U0_width_out_write, "hls_ComputeIntegrals_U0_width_out_write");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_ap_start, "hls_ComputeVectors_U0_ap_start");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_ap_done, "hls_ComputeVectors_U0_ap_done");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_ap_continue, "hls_ComputeVectors_U0_ap_continue");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_ap_idle, "hls_ComputeVectors_U0_ap_idle");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_ap_ready, "hls_ComputeVectors_U0_ap_ready");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_A11_img_V_read, "hls_ComputeVectors_U0_A11_img_V_read");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_A12_img_V_read, "hls_ComputeVectors_U0_A12_img_V_read");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_A22_img_V_read, "hls_ComputeVectors_U0_A22_img_V_read");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_B1_img_V_read, "hls_ComputeVectors_U0_B1_img_V_read");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_B2_img_V_read, "hls_ComputeVectors_U0_B2_img_V_read");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_vx_img_TDATA, "hls_ComputeVectors_U0_vx_img_TDATA");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_vx_img_TVALID, "hls_ComputeVectors_U0_vx_img_TVALID");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_vx_img_TLAST, "hls_ComputeVectors_U0_vx_img_TLAST");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_vy_img_TDATA, "hls_ComputeVectors_U0_vy_img_TDATA");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_vy_img_TVALID, "hls_ComputeVectors_U0_vy_img_TVALID");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_vy_img_TLAST, "hls_ComputeVectors_U0_vy_img_TLAST");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_height_read, "hls_ComputeVectors_U0_height_read");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_width_read, "hls_ComputeVectors_U0_width_read");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_ap_return, "hls_ComputeVectors_U0_ap_return");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, flt1_img_channel_full_n, "flt1_img_channel_full_n");
    sc_trace(mVcdFile, flt1_img_channel_dout, "flt1_img_channel_dout");
    sc_trace(mVcdFile, flt1_img_channel_empty_n, "flt1_img_channel_empty_n");
    sc_trace(mVcdFile, flt2_img_channel_full_n, "flt2_img_channel_full_n");
    sc_trace(mVcdFile, flt2_img_channel_dout, "flt2_img_channel_dout");
    sc_trace(mVcdFile, flt2_img_channel_empty_n, "flt2_img_channel_empty_n");
    sc_trace(mVcdFile, height_c_full_n, "height_c_full_n");
    sc_trace(mVcdFile, height_c_dout, "height_c_dout");
    sc_trace(mVcdFile, height_c_empty_n, "height_c_empty_n");
    sc_trace(mVcdFile, width_c_full_n, "width_c_full_n");
    sc_trace(mVcdFile, width_c_dout, "width_c_dout");
    sc_trace(mVcdFile, width_c_empty_n, "width_c_empty_n");
    sc_trace(mVcdFile, Dx1_img_channel_full_n, "Dx1_img_channel_full_n");
    sc_trace(mVcdFile, Dx1_img_channel_dout, "Dx1_img_channel_dout");
    sc_trace(mVcdFile, Dx1_img_channel_empty_n, "Dx1_img_channel_empty_n");
    sc_trace(mVcdFile, Dy1_img_channel_full_n, "Dy1_img_channel_full_n");
    sc_trace(mVcdFile, Dy1_img_channel_dout, "Dy1_img_channel_dout");
    sc_trace(mVcdFile, Dy1_img_channel_empty_n, "Dy1_img_channel_empty_n");
    sc_trace(mVcdFile, Dt_img_channel_full_n, "Dt_img_channel_full_n");
    sc_trace(mVcdFile, Dt_img_channel_dout, "Dt_img_channel_dout");
    sc_trace(mVcdFile, Dt_img_channel_empty_n, "Dt_img_channel_empty_n");
    sc_trace(mVcdFile, height_c9_full_n, "height_c9_full_n");
    sc_trace(mVcdFile, height_c9_dout, "height_c9_dout");
    sc_trace(mVcdFile, height_c9_empty_n, "height_c9_empty_n");
    sc_trace(mVcdFile, width_c10_full_n, "width_c10_full_n");
    sc_trace(mVcdFile, width_c10_dout, "width_c10_dout");
    sc_trace(mVcdFile, width_c10_empty_n, "width_c10_empty_n");
    sc_trace(mVcdFile, A11_img_channel_full_n, "A11_img_channel_full_n");
    sc_trace(mVcdFile, A11_img_channel_dout, "A11_img_channel_dout");
    sc_trace(mVcdFile, A11_img_channel_empty_n, "A11_img_channel_empty_n");
    sc_trace(mVcdFile, A12_img_channel_full_n, "A12_img_channel_full_n");
    sc_trace(mVcdFile, A12_img_channel_dout, "A12_img_channel_dout");
    sc_trace(mVcdFile, A12_img_channel_empty_n, "A12_img_channel_empty_n");
    sc_trace(mVcdFile, A22_img_channel_full_n, "A22_img_channel_full_n");
    sc_trace(mVcdFile, A22_img_channel_dout, "A22_img_channel_dout");
    sc_trace(mVcdFile, A22_img_channel_empty_n, "A22_img_channel_empty_n");
    sc_trace(mVcdFile, B1_img_channel_full_n, "B1_img_channel_full_n");
    sc_trace(mVcdFile, B1_img_channel_dout, "B1_img_channel_dout");
    sc_trace(mVcdFile, B1_img_channel_empty_n, "B1_img_channel_empty_n");
    sc_trace(mVcdFile, B2_img_channel_full_n, "B2_img_channel_full_n");
    sc_trace(mVcdFile, B2_img_channel_dout, "B2_img_channel_dout");
    sc_trace(mVcdFile, B2_img_channel_empty_n, "B2_img_channel_empty_n");
    sc_trace(mVcdFile, height_c11_full_n, "height_c11_full_n");
    sc_trace(mVcdFile, height_c11_dout, "height_c11_dout");
    sc_trace(mVcdFile, height_c11_empty_n, "height_c11_empty_n");
    sc_trace(mVcdFile, width_c12_full_n, "width_c12_full_n");
    sc_trace(mVcdFile, width_c12_dout, "width_c12_dout");
    sc_trace(mVcdFile, width_c12_empty_n, "width_c12_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, start_for_hls_SpatialTemporalD_U0_din, "start_for_hls_SpatialTemporalD_U0_din");
    sc_trace(mVcdFile, start_for_hls_SpatialTemporalD_U0_full_n, "start_for_hls_SpatialTemporalD_U0_full_n");
    sc_trace(mVcdFile, start_for_hls_SpatialTemporalD_U0_dout, "start_for_hls_SpatialTemporalD_U0_dout");
    sc_trace(mVcdFile, start_for_hls_SpatialTemporalD_U0_empty_n, "start_for_hls_SpatialTemporalD_U0_empty_n");
    sc_trace(mVcdFile, start_for_hls_ComputeIntegrals_U0_din, "start_for_hls_ComputeIntegrals_U0_din");
    sc_trace(mVcdFile, start_for_hls_ComputeIntegrals_U0_full_n, "start_for_hls_ComputeIntegrals_U0_full_n");
    sc_trace(mVcdFile, start_for_hls_ComputeIntegrals_U0_dout, "start_for_hls_ComputeIntegrals_U0_dout");
    sc_trace(mVcdFile, start_for_hls_ComputeIntegrals_U0_empty_n, "start_for_hls_ComputeIntegrals_U0_empty_n");
    sc_trace(mVcdFile, start_for_hls_ComputeVectors_U0_din, "start_for_hls_ComputeVectors_U0_din");
    sc_trace(mVcdFile, start_for_hls_ComputeVectors_U0_full_n, "start_for_hls_ComputeVectors_U0_full_n");
    sc_trace(mVcdFile, start_for_hls_ComputeVectors_U0_dout, "start_for_hls_ComputeVectors_U0_dout");
    sc_trace(mVcdFile, start_for_hls_ComputeVectors_U0_empty_n, "start_for_hls_ComputeVectors_U0_empty_n");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_start_full_n, "hls_ComputeVectors_U0_start_full_n");
    sc_trace(mVcdFile, hls_ComputeVectors_U0_start_write, "hls_ComputeVectors_U0_start_write");
    sc_trace(mVcdFile, ap_return, "ap_return");
#endif

    }
    mHdltvinHandle.open("hls_LK.hdltvin.dat");
    mHdltvoutHandle.open("hls_LK.hdltvout.dat");
}

hls_LK::~hls_LK() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete hls_LK_CONTROL_BUS_s_axi_U;
    delete hls_twoIsotropicFilt_U0;
    delete hls_SpatialTemporalD_U0;
    delete hls_ComputeIntegrals_U0;
    delete hls_ComputeVectors_U0;
    delete flt1_img_channel_U;
    delete flt2_img_channel_U;
    delete height_c_U;
    delete width_c_U;
    delete Dx1_img_channel_U;
    delete Dy1_img_channel_U;
    delete Dt_img_channel_U;
    delete height_c9_U;
    delete width_c10_U;
    delete A11_img_channel_U;
    delete A12_img_channel_U;
    delete A22_img_channel_U;
    delete B1_img_channel_U;
    delete B2_img_channel_U;
    delete height_c11_U;
    delete width_c12_U;
    delete start_for_hls_SpatialTemporalD_U0_U;
    delete start_for_hls_ComputeIntegrals_U0_U;
    delete start_for_hls_ComputeVectors_U0_U;
}

void hls_LK::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void hls_LK::thread_ap_done() {
    ap_done = hls_ComputeVectors_U0_ap_done.read();
}

void hls_LK::thread_ap_idle() {
    ap_idle = (hls_twoIsotropicFilt_U0_ap_idle.read() & hls_SpatialTemporalD_U0_ap_idle.read() & hls_ComputeIntegrals_U0_ap_idle.read() & hls_ComputeVectors_U0_ap_idle.read());
}

void hls_LK::thread_ap_ready() {
    ap_ready = hls_twoIsotropicFilt_U0_ap_ready.read();
}

void hls_LK::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void hls_LK::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void hls_LK::thread_ap_sync_done() {
    ap_sync_done = hls_ComputeVectors_U0_ap_done.read();
}

void hls_LK::thread_ap_sync_ready() {
    ap_sync_ready = hls_twoIsotropicFilt_U0_ap_ready.read();
}

void hls_LK::thread_hls_ComputeIntegrals_U0_ap_continue() {
    hls_ComputeIntegrals_U0_ap_continue = ap_const_logic_1;
}

void hls_LK::thread_hls_ComputeIntegrals_U0_ap_start() {
    hls_ComputeIntegrals_U0_ap_start = start_for_hls_ComputeIntegrals_U0_empty_n.read();
}

void hls_LK::thread_hls_ComputeVectors_U0_ap_continue() {
    hls_ComputeVectors_U0_ap_continue = ap_const_logic_1;
}

void hls_LK::thread_hls_ComputeVectors_U0_ap_start() {
    hls_ComputeVectors_U0_ap_start = start_for_hls_ComputeVectors_U0_empty_n.read();
}

void hls_LK::thread_hls_ComputeVectors_U0_start_full_n() {
    hls_ComputeVectors_U0_start_full_n = ap_const_logic_1;
}

void hls_LK::thread_hls_ComputeVectors_U0_start_write() {
    hls_ComputeVectors_U0_start_write = ap_const_logic_0;
}

void hls_LK::thread_hls_SpatialTemporalD_U0_ap_continue() {
    hls_SpatialTemporalD_U0_ap_continue = ap_const_logic_1;
}

void hls_LK::thread_hls_SpatialTemporalD_U0_ap_start() {
    hls_SpatialTemporalD_U0_ap_start = start_for_hls_SpatialTemporalD_U0_empty_n.read();
}

void hls_LK::thread_hls_twoIsotropicFilt_U0_ap_continue() {
    hls_twoIsotropicFilt_U0_ap_continue = ap_const_logic_1;
}

void hls_LK::thread_hls_twoIsotropicFilt_U0_ap_start() {
    hls_twoIsotropicFilt_U0_ap_start = ap_start.read();
}

void hls_LK::thread_inp1_img_TREADY() {
    inp1_img_TREADY = hls_twoIsotropicFilt_U0_inp1_img_TREADY.read();
}

void hls_LK::thread_inp2_img_TREADY() {
    inp2_img_TREADY = hls_twoIsotropicFilt_U0_inp2_img_TREADY.read();
}

void hls_LK::thread_start_for_hls_ComputeIntegrals_U0_din() {
    start_for_hls_ComputeIntegrals_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void hls_LK::thread_start_for_hls_ComputeVectors_U0_din() {
    start_for_hls_ComputeVectors_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void hls_LK::thread_start_for_hls_SpatialTemporalD_U0_din() {
    start_for_hls_SpatialTemporalD_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void hls_LK::thread_vx_img_TDATA() {
    vx_img_TDATA = hls_ComputeVectors_U0_vx_img_TDATA.read();
}

void hls_LK::thread_vx_img_TLAST() {
    vx_img_TLAST = hls_ComputeVectors_U0_vx_img_TLAST.read();
}

void hls_LK::thread_vx_img_TVALID() {
    vx_img_TVALID = hls_ComputeVectors_U0_vx_img_TVALID.read();
}

void hls_LK::thread_vy_img_TDATA() {
    vy_img_TDATA = hls_ComputeVectors_U0_vy_img_TDATA.read();
}

void hls_LK::thread_vy_img_TLAST() {
    vy_img_TLAST = hls_ComputeVectors_U0_vy_img_TLAST.read();
}

void hls_LK::thread_vy_img_TVALID() {
    vy_img_TVALID = hls_ComputeVectors_U0_vy_img_TVALID.read();
}

void hls_LK::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWVALID\" :  \"" << s_axi_CONTROL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWREADY\" :  \"" << s_axi_CONTROL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWADDR\" :  \"" << s_axi_CONTROL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WVALID\" :  \"" << s_axi_CONTROL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_WREADY\" :  \"" << s_axi_CONTROL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WDATA\" :  \"" << s_axi_CONTROL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WSTRB\" :  \"" << s_axi_CONTROL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARVALID\" :  \"" << s_axi_CONTROL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARREADY\" :  \"" << s_axi_CONTROL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARADDR\" :  \"" << s_axi_CONTROL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RVALID\" :  \"" << s_axi_CONTROL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_RREADY\" :  \"" << s_axi_CONTROL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RDATA\" :  \"" << s_axi_CONTROL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RRESP\" :  \"" << s_axi_CONTROL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BVALID\" :  \"" << s_axi_CONTROL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_BREADY\" :  \"" << s_axi_CONTROL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BRESP\" :  \"" << s_axi_CONTROL_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inp1_img_TDATA\" :  \"" << inp1_img_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inp1_img_TLAST\" :  \"" << inp1_img_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inp2_img_TDATA\" :  \"" << inp2_img_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inp2_img_TLAST\" :  \"" << inp2_img_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vx_img_TDATA\" :  \"" << vx_img_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vx_img_TLAST\" :  \"" << vx_img_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vy_img_TDATA\" :  \"" << vy_img_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vy_img_TLAST\" :  \"" << vy_img_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inp1_img_TVALID\" :  \"" << inp1_img_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inp1_img_TREADY\" :  \"" << inp1_img_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inp2_img_TVALID\" :  \"" << inp2_img_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inp2_img_TREADY\" :  \"" << inp2_img_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vx_img_TVALID\" :  \"" << vx_img_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"vx_img_TREADY\" :  \"" << vx_img_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vy_img_TVALID\" :  \"" << vy_img_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"vy_img_TREADY\" :  \"" << vy_img_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

