// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_isotropic_kernel (
        ap_clk,
        ap_rst,
        window_0_V_read,
        window_1_V_read,
        window_2_V_read,
        window_3_V_read,
        window_4_V_read,
        window_5_V_read,
        window_6_V_read,
        window_7_V_read,
        window_8_V_read,
        window_9_V_read,
        window_10_V_read,
        window_11_V_read,
        window_12_V_read,
        window_13_V_read,
        window_14_V_read,
        window_15_V_read,
        window_16_V_read,
        window_17_V_read,
        window_18_V_read,
        window_19_V_read,
        window_20_V_read,
        window_21_V_read,
        window_22_V_read,
        window_23_V_read,
        window_24_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [23:0] window_0_V_read;
input  [23:0] window_1_V_read;
input  [23:0] window_2_V_read;
input  [23:0] window_3_V_read;
input  [23:0] window_4_V_read;
input  [23:0] window_5_V_read;
input  [23:0] window_6_V_read;
input  [23:0] window_7_V_read;
input  [23:0] window_8_V_read;
input  [23:0] window_9_V_read;
input  [23:0] window_10_V_read;
input  [23:0] window_11_V_read;
input  [23:0] window_12_V_read;
input  [23:0] window_13_V_read;
input  [23:0] window_14_V_read;
input  [23:0] window_15_V_read;
input  [23:0] window_16_V_read;
input  [23:0] window_17_V_read;
input  [23:0] window_18_V_read;
input  [23:0] window_19_V_read;
input  [23:0] window_20_V_read;
input  [23:0] window_21_V_read;
input  [23:0] window_22_V_read;
input  [23:0] window_23_V_read;
input  [23:0] window_24_V_read;
output  [23:0] ap_return;
input   ap_ce;

reg[23:0] ap_return;

wire   [19:0] tmp15_fu_1550_p2;
reg   [19:0] tmp15_reg_1974;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [19:0] tmp16_fu_1562_p2;
reg   [19:0] tmp16_reg_1979;
wire   [18:0] tmp18_fu_1604_p2;
reg   [18:0] tmp18_reg_1984;
wire   [19:0] tmp24_fu_1614_p2;
reg   [19:0] tmp24_reg_1989;
wire   [19:0] tmp25_fu_1626_p2;
reg   [19:0] tmp25_reg_1994;
wire   [18:0] tmp27_fu_1668_p2;
reg   [18:0] tmp27_reg_1999;
wire   [11:0] tmp_41_fu_1712_p1;
reg   [11:0] tmp_41_reg_2004;
reg   [11:0] tmp_42_reg_2010;
wire   [15:0] tmp33_fu_1792_p2;
reg   [15:0] tmp33_reg_2016;
wire   [15:0] tmp36_fu_1812_p2;
reg   [15:0] tmp36_reg_2021;
wire    ap_block_pp0_stage0;
wire   [11:0] tmp_4_fu_236_p1;
wire   [11:0] p_Result_8_fu_240_p4;
wire   [11:0] tmp_6_fu_258_p1;
wire   [11:0] tmp_2_fu_270_p4;
wire   [13:0] ret_V_0_1_fu_262_p3;
wire   [14:0] tmp_71_0_1_cast_fu_288_p1;
wire   [14:0] tmp_71_0_cast_fu_250_p1;
wire   [14:0] accum1_1_0_1_fu_292_p2;
wire   [13:0] ret_V_4_0_1_fu_280_p3;
wire   [14:0] tmp_72_0_1_cast_fu_302_p1;
wire   [14:0] tmp_72_0_cast_fu_254_p1;
wire   [14:0] accum2_1_0_1_fu_306_p2;
wire   [11:0] tmp_7_fu_316_p1;
wire   [14:0] p_shl1_fu_320_p3;
wire   [12:0] p_shl2_fu_332_p3;
wire   [15:0] p_shl1_cast_fu_328_p1;
wire   [15:0] p_shl2_cast_fu_340_p1;
wire   [15:0] ret_V_0_2_fu_344_p2;
wire   [11:0] tmp_5_fu_354_p4;
wire   [14:0] p_shl3_fu_364_p3;
wire   [12:0] p_shl4_fu_376_p3;
wire   [15:0] p_shl3_cast_fu_372_p1;
wire   [15:0] p_shl4_cast_fu_384_p1;
wire   [15:0] ret_V_4_0_2_fu_388_p2;
wire  signed [18:0] ret_V_0_2_cast_fu_350_p1;
wire  signed [18:0] ret_V_4_0_2_cast_fu_394_p1;
wire   [11:0] tmp_9_fu_406_p1;
wire   [11:0] tmp_8_fu_418_p4;
wire   [13:0] ret_V_0_3_fu_410_p3;
wire   [13:0] ret_V_4_0_3_fu_428_p3;
wire   [11:0] tmp_11_fu_444_p1;
wire   [11:0] p_Result_8_0_4_fu_448_p4;
wire   [11:0] tmp_13_fu_466_p1;
wire   [11:0] tmp_s_fu_478_p4;
wire   [13:0] ret_V_1_fu_470_p3;
wire   [13:0] ret_V_4_1_fu_488_p3;
wire   [11:0] tmp_14_fu_504_p1;
wire   [11:0] tmp_1_fu_516_p4;
wire   [15:0] ret_V_1_1_fu_508_p3;
wire   [16:0] tmp_71_1_1_cast_cast_fu_534_p1;
wire   [16:0] accum1_1_0_1_cast_ca_fu_298_p1;
wire   [16:0] tmp1_fu_538_p2;
wire   [19:0] tmp1_cast_fu_544_p1;
wire   [19:0] tmp_71_0_2_cast_fu_398_p1;
wire   [14:0] tmp_71_1_cast_cast_fu_496_p1;
wire   [14:0] tmp_71_0_4_cast_cast_fu_458_p1;
wire   [14:0] tmp3_fu_554_p2;
wire   [15:0] tmp3_cast_fu_560_p1;
wire   [15:0] tmp_71_0_3_cast_cast_fu_436_p1;
wire   [15:0] tmp2_fu_564_p2;
wire   [19:0] tmp2_cast_fu_570_p1;
wire   [19:0] tmp_fu_548_p2;
wire   [15:0] ret_V_4_1_1_fu_526_p3;
wire   [16:0] tmp_72_1_1_cast_cast_fu_580_p1;
wire   [16:0] accum2_1_0_1_cast_ca_fu_312_p1;
wire   [16:0] tmp5_fu_584_p2;
wire   [19:0] tmp5_cast_fu_590_p1;
wire   [19:0] tmp_72_0_2_cast_fu_402_p1;
wire   [14:0] tmp_72_1_cast_cast_fu_500_p1;
wire   [14:0] tmp_72_0_4_cast_cast_fu_462_p1;
wire   [14:0] tmp7_fu_600_p2;
wire   [15:0] tmp7_cast_fu_606_p1;
wire   [15:0] tmp_72_0_3_cast_cast_fu_440_p1;
wire   [15:0] tmp6_fu_610_p2;
wire   [19:0] tmp6_cast_fu_616_p1;
wire   [19:0] tmp4_fu_594_p2;
wire   [11:0] tmp_16_fu_626_p1;
wire   [16:0] p_shl5_fu_630_p3;
wire   [14:0] p_shl6_fu_642_p3;
wire   [17:0] p_shl5_cast_fu_638_p1;
wire   [17:0] p_shl6_cast_fu_650_p1;
wire   [17:0] ret_V_1_2_fu_654_p2;
wire   [11:0] tmp_3_fu_664_p4;
wire   [16:0] p_shl7_fu_674_p3;
wire   [14:0] p_shl8_fu_686_p3;
wire   [17:0] p_shl7_cast_fu_682_p1;
wire   [17:0] p_shl8_cast_fu_694_p1;
wire   [17:0] ret_V_4_1_2_fu_698_p2;
wire  signed [18:0] ret_V_1_2_cast_fu_660_p1;
wire  signed [18:0] ret_V_4_1_2_cast_fu_704_p1;
wire   [11:0] tmp_17_fu_716_p1;
wire   [11:0] tmp_10_fu_728_p4;
wire   [15:0] ret_V_1_3_fu_720_p3;
wire   [15:0] ret_V_4_1_3_fu_738_p3;
wire   [11:0] tmp_18_fu_754_p1;
wire   [11:0] tmp_12_fu_766_p4;
wire   [13:0] ret_V_1_4_fu_758_p3;
wire   [13:0] ret_V_4_1_4_fu_776_p3;
wire   [11:0] tmp_19_fu_792_p1;
wire   [14:0] p_shl9_fu_796_p3;
wire   [12:0] p_shl10_fu_808_p3;
wire   [15:0] p_shl9_cast_fu_804_p1;
wire   [15:0] p_shl10_cast_fu_816_p1;
wire   [15:0] ret_V_2_fu_820_p2;
wire   [11:0] tmp_15_fu_830_p4;
wire   [14:0] p_shl11_fu_840_p3;
wire   [12:0] p_shl12_fu_852_p3;
wire   [15:0] p_shl11_cast_fu_848_p1;
wire   [15:0] p_shl12_cast_fu_860_p1;
wire   [15:0] ret_V_4_2_fu_864_p2;
wire  signed [18:0] ret_V_2_cast_fu_826_p1;
wire   [19:0] accum1_1_1_1_fu_574_p2;
wire   [19:0] tmp_71_1_2_cast_fu_708_p1;
wire   [16:0] tmp_71_1_3_cast_cast_fu_746_p1;
wire   [16:0] tmp_71_1_4_cast_cast_fu_784_p1;
wire   [16:0] tmp10_fu_884_p2;
wire   [19:0] tmp10_cast_fu_890_p1;
wire   [19:0] tmp_71_2_cast_cast_fu_874_p1;
wire   [19:0] tmp9_fu_894_p2;
wire   [19:0] tmp8_fu_878_p2;
wire  signed [18:0] ret_V_4_2_cast_fu_870_p1;
wire   [19:0] accum2_1_1_1_fu_620_p2;
wire   [19:0] tmp_72_1_2_cast_fu_712_p1;
wire   [16:0] tmp_72_1_3_cast_cast_fu_750_p1;
wire   [16:0] tmp_72_1_4_cast_cast_fu_788_p1;
wire   [16:0] tmp13_fu_916_p2;
wire   [19:0] tmp13_cast_fu_922_p1;
wire   [19:0] tmp_72_2_cast_cast_fu_906_p1;
wire   [19:0] tmp12_fu_926_p2;
wire   [19:0] tmp11_fu_910_p2;
wire   [11:0] tmp_20_fu_938_p1;
wire   [16:0] p_shl13_fu_942_p3;
wire   [14:0] p_shl14_fu_954_p3;
wire   [17:0] p_shl13_cast_fu_950_p1;
wire   [17:0] p_shl14_cast_fu_962_p1;
wire   [17:0] ret_V_2_1_fu_966_p2;
wire   [11:0] tmp_21_fu_976_p4;
wire   [16:0] p_shl34_fu_986_p3;
wire   [14:0] p_shl35_fu_998_p3;
wire   [17:0] p_shl34_cast_fu_994_p1;
wire   [17:0] p_shl35_cast_fu_1006_p1;
wire   [17:0] ret_V_4_2_1_fu_1010_p2;
wire  signed [18:0] ret_V_2_1_cast_fu_972_p1;
wire  signed [18:0] ret_V_4_2_1_cast_fu_1016_p1;
wire   [11:0] tmp_22_fu_1028_p1;
wire   [16:0] p_shl32_fu_1032_p3;
wire   [13:0] p_shl33_fu_1044_p3;
wire   [17:0] p_shl32_cast_fu_1040_p1;
wire   [17:0] p_shl33_cast_fu_1052_p1;
wire   [11:0] tmp_23_fu_1062_p4;
wire   [16:0] p_shl30_fu_1072_p3;
wire   [13:0] p_shl31_fu_1084_p3;
wire   [17:0] p_shl30_cast_fu_1080_p1;
wire   [17:0] p_shl31_cast_fu_1092_p1;
wire   [17:0] ret_V_2_2_fu_1056_p2;
wire   [17:0] ret_V_4_2_2_fu_1096_p2;
wire   [11:0] tmp_24_fu_1110_p1;
wire   [16:0] p_shl28_fu_1114_p3;
wire   [14:0] p_shl29_fu_1126_p3;
wire   [17:0] p_shl28_cast_fu_1122_p1;
wire   [17:0] p_shl29_cast_fu_1134_p1;
wire   [17:0] ret_V_2_3_fu_1138_p2;
wire   [11:0] tmp_25_fu_1148_p4;
wire   [16:0] p_shl26_fu_1158_p3;
wire   [14:0] p_shl27_fu_1170_p3;
wire   [17:0] p_shl26_cast_fu_1166_p1;
wire   [17:0] p_shl27_cast_fu_1178_p1;
wire   [17:0] ret_V_4_2_3_fu_1182_p2;
wire  signed [18:0] ret_V_2_3_cast_fu_1144_p1;
wire  signed [18:0] ret_V_4_2_3_cast_fu_1188_p1;
wire   [11:0] tmp_26_fu_1200_p1;
wire   [14:0] p_shl24_fu_1204_p3;
wire   [12:0] p_shl25_fu_1216_p3;
wire   [15:0] p_shl24_cast_fu_1212_p1;
wire   [15:0] p_shl25_cast_fu_1224_p1;
wire   [15:0] ret_V_2_4_fu_1228_p2;
wire   [11:0] tmp_27_fu_1238_p4;
wire   [14:0] p_shl22_fu_1248_p3;
wire   [12:0] p_shl23_fu_1260_p3;
wire   [15:0] p_shl22_cast_fu_1256_p1;
wire   [15:0] p_shl23_cast_fu_1268_p1;
wire   [15:0] ret_V_4_2_4_fu_1272_p2;
wire  signed [18:0] ret_V_2_4_cast_fu_1234_p1;
wire  signed [18:0] ret_V_4_2_4_cast_fu_1278_p1;
wire   [11:0] tmp_28_fu_1290_p1;
wire   [11:0] tmp_29_fu_1302_p4;
wire   [13:0] ret_V_3_fu_1294_p3;
wire   [13:0] ret_V_4_3_fu_1312_p3;
wire   [11:0] tmp_30_fu_1328_p1;
wire   [11:0] tmp_31_fu_1340_p4;
wire   [15:0] ret_V_3_1_fu_1332_p3;
wire   [15:0] ret_V_4_3_1_fu_1350_p3;
wire   [11:0] tmp_32_fu_1366_p1;
wire   [16:0] p_shl20_fu_1370_p3;
wire   [14:0] p_shl21_fu_1382_p3;
wire   [17:0] p_shl20_cast_fu_1378_p1;
wire   [17:0] p_shl21_cast_fu_1390_p1;
wire   [17:0] ret_V_3_2_fu_1394_p2;
wire   [11:0] tmp_33_fu_1404_p4;
wire   [16:0] p_shl18_fu_1414_p3;
wire   [14:0] p_shl19_fu_1426_p3;
wire   [17:0] p_shl18_cast_fu_1422_p1;
wire   [17:0] p_shl19_cast_fu_1434_p1;
wire   [17:0] ret_V_4_3_2_fu_1438_p2;
wire  signed [18:0] ret_V_3_2_cast_fu_1400_p1;
wire  signed [18:0] ret_V_4_3_2_cast_fu_1444_p1;
wire   [11:0] tmp_34_fu_1456_p1;
wire   [11:0] tmp_35_fu_1468_p4;
wire   [15:0] ret_V_3_3_fu_1460_p3;
wire   [15:0] ret_V_4_3_3_fu_1478_p3;
wire   [11:0] tmp_36_fu_1494_p1;
wire   [11:0] tmp_37_fu_1506_p4;
wire   [13:0] ret_V_3_4_fu_1498_p3;
wire   [13:0] ret_V_4_3_4_fu_1516_p3;
wire   [11:0] tmp_38_fu_1532_p1;
wire   [19:0] accum1_1_2_fu_900_p2;
wire   [19:0] tmp_71_2_1_cast_fu_1020_p1;
wire   [19:0] tmp_71_2_4_cast_cast_fu_1282_p1;
wire   [19:0] tmp_71_3_2_cast_cast_fu_1448_p1;
wire   [19:0] tmp17_fu_1556_p2;
wire   [19:0] tmp_71_2_3_cast_cast_fu_1192_p1;
wire   [16:0] tmp_71_3_1_cast_cast_fu_1358_p1;
wire   [16:0] tmp_71_3_3_cast_cast_fu_1486_p1;
wire   [16:0] tmp20_fu_1568_p2;
wire   [18:0] tmp20_cast_fu_1574_p1;
wire   [18:0] tmp_71_2_2_cast_cast_fu_1102_p1;
wire   [14:0] tmp_71_3_4_cast_cast_fu_1524_p1;
wire   [14:0] tmp_71_4_cast_cast_fu_1546_p1;
wire   [14:0] tmp22_fu_1584_p2;
wire   [15:0] tmp22_cast_fu_1590_p1;
wire   [15:0] tmp_71_3_cast_cast_fu_1320_p1;
wire   [15:0] tmp21_fu_1594_p2;
wire   [18:0] tmp21_cast_fu_1600_p1;
wire   [18:0] tmp19_fu_1578_p2;
wire   [11:0] p_Result_8_4_fu_1536_p4;
wire   [19:0] accum2_1_2_fu_932_p2;
wire   [19:0] tmp_72_2_1_cast_fu_1024_p1;
wire   [19:0] tmp_72_2_4_cast_cast_fu_1286_p1;
wire   [19:0] tmp_72_3_2_cast_cast_fu_1452_p1;
wire   [19:0] tmp26_fu_1620_p2;
wire   [19:0] tmp_72_2_3_cast_cast_fu_1196_p1;
wire   [16:0] tmp_72_3_1_cast_cast_fu_1362_p1;
wire   [16:0] tmp_72_3_3_cast_cast_fu_1490_p1;
wire   [16:0] tmp29_fu_1632_p2;
wire   [18:0] tmp29_cast_fu_1638_p1;
wire   [18:0] tmp_72_2_2_cast_cast_fu_1106_p1;
wire   [14:0] tmp_72_3_4_cast_cast_fu_1528_p1;
wire   [14:0] tmp_72_4_cast_cast_fu_1610_p1;
wire   [14:0] tmp31_fu_1648_p2;
wire   [15:0] tmp31_cast_fu_1654_p1;
wire   [15:0] tmp_72_3_cast_cast_fu_1324_p1;
wire   [15:0] tmp30_fu_1658_p2;
wire   [18:0] tmp30_cast_fu_1664_p1;
wire   [18:0] tmp28_fu_1642_p2;
wire   [11:0] tmp_39_fu_1674_p1;
wire   [11:0] tmp_40_fu_1686_p4;
wire   [13:0] ret_V_414_1_fu_1678_p3;
wire   [13:0] ret_V_4_4_1_fu_1696_p3;
wire   [11:0] tmp_43_fu_1726_p1;
wire   [11:0] tmp_44_fu_1738_p4;
wire   [13:0] ret_V_414_3_fu_1730_p3;
wire   [13:0] ret_V_4_4_3_fu_1748_p3;
wire   [11:0] tmp_45_fu_1764_p1;
wire   [14:0] tmp_71_4_3_cast_cast_fu_1756_p1;
wire   [14:0] tmp_71_4_4_cast_cast_fu_1778_p1;
wire   [14:0] tmp34_fu_1782_p2;
wire   [15:0] tmp34_cast_fu_1788_p1;
wire   [15:0] tmp_71_4_1_cast_cast_fu_1704_p1;
wire   [11:0] p_Result_8_4_4_fu_1768_p4;
wire   [14:0] tmp_72_4_3_cast_cast_fu_1760_p1;
wire   [14:0] tmp_72_4_4_cast_cast_fu_1798_p1;
wire   [14:0] tmp37_fu_1802_p2;
wire   [15:0] tmp37_cast_fu_1808_p1;
wire   [15:0] tmp_72_4_1_cast_cast_fu_1708_p1;
wire   [19:0] tmp18_cast_fu_1822_p1;
wire   [19:0] tmp14_fu_1818_p2;
wire   [19:0] tmp27_cast_fu_1835_p1;
wire   [19:0] tmp23_fu_1831_p2;
wire   [14:0] p_shl16_fu_1844_p3;
wire   [12:0] p_shl17_fu_1855_p3;
wire   [15:0] p_shl16_cast_fu_1851_p1;
wire   [15:0] p_shl17_cast_fu_1862_p1;
wire   [15:0] ret_V_414_2_fu_1866_p2;
wire   [14:0] p_shl_fu_1876_p3;
wire   [12:0] p_shl15_fu_1887_p3;
wire   [15:0] p_shl_cast_fu_1883_p1;
wire   [15:0] p_shl15_cast_fu_1894_p1;
wire   [15:0] ret_V_4_4_2_fu_1898_p2;
wire  signed [18:0] ret_V_414_2_cast_fu_1872_p1;
wire  signed [18:0] ret_V_4_4_2_cast_fu_1904_p1;
wire   [19:0] accum1_1_4_fu_1825_p2;
wire   [19:0] tmp_71_4_2_cast_cast_fu_1908_p1;
wire   [19:0] tmp33_cast_fu_1922_p1;
wire   [19:0] tmp32_fu_1916_p2;
wire   [19:0] accum2_1_4_fu_1838_p2;
wire   [19:0] tmp_72_4_2_cast_cast_fu_1912_p1;
wire   [19:0] tmp36_cast_fu_1937_p1;
wire   [19:0] tmp35_fu_1931_p2;
wire   [19:0] accum1_1_4_4_fu_1925_p2;
wire   [19:0] accum2_1_4_4_fu_1940_p2;
wire   [11:0] final_val2_V_fu_1956_p4;
wire   [11:0] final_val1_V_fu_1946_p4;
wire   [23:0] p_Result_s_fu_1966_p3;
reg    ap_ce_reg;
reg   [23:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= p_Result_s_fu_1966_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        tmp15_reg_1974 <= tmp15_fu_1550_p2;
        tmp16_reg_1979[19 : 1] <= tmp16_fu_1562_p2[19 : 1];
        tmp18_reg_1984 <= tmp18_fu_1604_p2;
        tmp24_reg_1989 <= tmp24_fu_1614_p2;
        tmp25_reg_1994[19 : 1] <= tmp25_fu_1626_p2[19 : 1];
        tmp27_reg_1999 <= tmp27_fu_1668_p2;
        tmp33_reg_2016 <= tmp33_fu_1792_p2;
        tmp36_reg_2021 <= tmp36_fu_1812_p2;
        tmp_41_reg_2004 <= tmp_41_fu_1712_p1;
        tmp_42_reg_2010 <= {{window_22_V_read[23:12]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = p_Result_s_fu_1966_p3;
    end
end

assign accum1_1_0_1_cast_ca_fu_298_p1 = accum1_1_0_1_fu_292_p2;

assign accum1_1_0_1_fu_292_p2 = (tmp_71_0_1_cast_fu_288_p1 + tmp_71_0_cast_fu_250_p1);

assign accum1_1_1_1_fu_574_p2 = (tmp2_cast_fu_570_p1 + tmp_fu_548_p2);

assign accum1_1_2_fu_900_p2 = (tmp9_fu_894_p2 + tmp8_fu_878_p2);

assign accum1_1_4_4_fu_1925_p2 = (tmp33_cast_fu_1922_p1 + tmp32_fu_1916_p2);

assign accum1_1_4_fu_1825_p2 = (tmp18_cast_fu_1822_p1 + tmp14_fu_1818_p2);

assign accum2_1_0_1_cast_ca_fu_312_p1 = accum2_1_0_1_fu_306_p2;

assign accum2_1_0_1_fu_306_p2 = (tmp_72_0_1_cast_fu_302_p1 + tmp_72_0_cast_fu_254_p1);

assign accum2_1_1_1_fu_620_p2 = (tmp6_cast_fu_616_p1 + tmp4_fu_594_p2);

assign accum2_1_2_fu_932_p2 = (tmp12_fu_926_p2 + tmp11_fu_910_p2);

assign accum2_1_4_4_fu_1940_p2 = (tmp36_cast_fu_1937_p1 + tmp35_fu_1931_p2);

assign accum2_1_4_fu_1838_p2 = (tmp27_cast_fu_1835_p1 + tmp23_fu_1831_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign final_val1_V_fu_1946_p4 = {{accum1_1_4_4_fu_1925_p2[19:8]}};

assign final_val2_V_fu_1956_p4 = {{accum2_1_4_4_fu_1940_p2[19:8]}};

assign p_Result_8_0_4_fu_448_p4 = {{window_4_V_read[23:12]}};

assign p_Result_8_4_4_fu_1768_p4 = {{window_24_V_read[23:12]}};

assign p_Result_8_4_fu_1536_p4 = {{window_20_V_read[23:12]}};

assign p_Result_8_fu_240_p4 = {{window_0_V_read[23:12]}};

assign p_Result_s_fu_1966_p3 = {{final_val2_V_fu_1956_p4}, {final_val1_V_fu_1946_p4}};

assign p_shl10_cast_fu_816_p1 = p_shl10_fu_808_p3;

assign p_shl10_fu_808_p3 = {{tmp_19_fu_792_p1}, {1'd0}};

assign p_shl11_cast_fu_848_p1 = p_shl11_fu_840_p3;

assign p_shl11_fu_840_p3 = {{tmp_15_fu_830_p4}, {3'd0}};

assign p_shl12_cast_fu_860_p1 = p_shl12_fu_852_p3;

assign p_shl12_fu_852_p3 = {{tmp_15_fu_830_p4}, {1'd0}};

assign p_shl13_cast_fu_950_p1 = p_shl13_fu_942_p3;

assign p_shl13_fu_942_p3 = {{tmp_20_fu_938_p1}, {5'd0}};

assign p_shl14_cast_fu_962_p1 = p_shl14_fu_954_p3;

assign p_shl14_fu_954_p3 = {{tmp_20_fu_938_p1}, {3'd0}};

assign p_shl15_cast_fu_1894_p1 = p_shl15_fu_1887_p3;

assign p_shl15_fu_1887_p3 = {{tmp_42_reg_2010}, {1'd0}};

assign p_shl16_cast_fu_1851_p1 = p_shl16_fu_1844_p3;

assign p_shl16_fu_1844_p3 = {{tmp_41_reg_2004}, {3'd0}};

assign p_shl17_cast_fu_1862_p1 = p_shl17_fu_1855_p3;

assign p_shl17_fu_1855_p3 = {{tmp_41_reg_2004}, {1'd0}};

assign p_shl18_cast_fu_1422_p1 = p_shl18_fu_1414_p3;

assign p_shl18_fu_1414_p3 = {{tmp_33_fu_1404_p4}, {5'd0}};

assign p_shl19_cast_fu_1434_p1 = p_shl19_fu_1426_p3;

assign p_shl19_fu_1426_p3 = {{tmp_33_fu_1404_p4}, {3'd0}};

assign p_shl1_cast_fu_328_p1 = p_shl1_fu_320_p3;

assign p_shl1_fu_320_p3 = {{tmp_7_fu_316_p1}, {3'd0}};

assign p_shl20_cast_fu_1378_p1 = p_shl20_fu_1370_p3;

assign p_shl20_fu_1370_p3 = {{tmp_32_fu_1366_p1}, {5'd0}};

assign p_shl21_cast_fu_1390_p1 = p_shl21_fu_1382_p3;

assign p_shl21_fu_1382_p3 = {{tmp_32_fu_1366_p1}, {3'd0}};

assign p_shl22_cast_fu_1256_p1 = p_shl22_fu_1248_p3;

assign p_shl22_fu_1248_p3 = {{tmp_27_fu_1238_p4}, {3'd0}};

assign p_shl23_cast_fu_1268_p1 = p_shl23_fu_1260_p3;

assign p_shl23_fu_1260_p3 = {{tmp_27_fu_1238_p4}, {1'd0}};

assign p_shl24_cast_fu_1212_p1 = p_shl24_fu_1204_p3;

assign p_shl24_fu_1204_p3 = {{tmp_26_fu_1200_p1}, {3'd0}};

assign p_shl25_cast_fu_1224_p1 = p_shl25_fu_1216_p3;

assign p_shl25_fu_1216_p3 = {{tmp_26_fu_1200_p1}, {1'd0}};

assign p_shl26_cast_fu_1166_p1 = p_shl26_fu_1158_p3;

assign p_shl26_fu_1158_p3 = {{tmp_25_fu_1148_p4}, {5'd0}};

assign p_shl27_cast_fu_1178_p1 = p_shl27_fu_1170_p3;

assign p_shl27_fu_1170_p3 = {{tmp_25_fu_1148_p4}, {3'd0}};

assign p_shl28_cast_fu_1122_p1 = p_shl28_fu_1114_p3;

assign p_shl28_fu_1114_p3 = {{tmp_24_fu_1110_p1}, {5'd0}};

assign p_shl29_cast_fu_1134_p1 = p_shl29_fu_1126_p3;

assign p_shl29_fu_1126_p3 = {{tmp_24_fu_1110_p1}, {3'd0}};

assign p_shl2_cast_fu_340_p1 = p_shl2_fu_332_p3;

assign p_shl2_fu_332_p3 = {{tmp_7_fu_316_p1}, {1'd0}};

assign p_shl30_cast_fu_1080_p1 = p_shl30_fu_1072_p3;

assign p_shl30_fu_1072_p3 = {{tmp_23_fu_1062_p4}, {5'd0}};

assign p_shl31_cast_fu_1092_p1 = p_shl31_fu_1084_p3;

assign p_shl31_fu_1084_p3 = {{tmp_23_fu_1062_p4}, {2'd0}};

assign p_shl32_cast_fu_1040_p1 = p_shl32_fu_1032_p3;

assign p_shl32_fu_1032_p3 = {{tmp_22_fu_1028_p1}, {5'd0}};

assign p_shl33_cast_fu_1052_p1 = p_shl33_fu_1044_p3;

assign p_shl33_fu_1044_p3 = {{tmp_22_fu_1028_p1}, {2'd0}};

assign p_shl34_cast_fu_994_p1 = p_shl34_fu_986_p3;

assign p_shl34_fu_986_p3 = {{tmp_21_fu_976_p4}, {5'd0}};

assign p_shl35_cast_fu_1006_p1 = p_shl35_fu_998_p3;

assign p_shl35_fu_998_p3 = {{tmp_21_fu_976_p4}, {3'd0}};

assign p_shl3_cast_fu_372_p1 = p_shl3_fu_364_p3;

assign p_shl3_fu_364_p3 = {{tmp_5_fu_354_p4}, {3'd0}};

assign p_shl4_cast_fu_384_p1 = p_shl4_fu_376_p3;

assign p_shl4_fu_376_p3 = {{tmp_5_fu_354_p4}, {1'd0}};

assign p_shl5_cast_fu_638_p1 = p_shl5_fu_630_p3;

assign p_shl5_fu_630_p3 = {{tmp_16_fu_626_p1}, {5'd0}};

assign p_shl6_cast_fu_650_p1 = p_shl6_fu_642_p3;

assign p_shl6_fu_642_p3 = {{tmp_16_fu_626_p1}, {3'd0}};

assign p_shl7_cast_fu_682_p1 = p_shl7_fu_674_p3;

assign p_shl7_fu_674_p3 = {{tmp_3_fu_664_p4}, {5'd0}};

assign p_shl8_cast_fu_694_p1 = p_shl8_fu_686_p3;

assign p_shl8_fu_686_p3 = {{tmp_3_fu_664_p4}, {3'd0}};

assign p_shl9_cast_fu_804_p1 = p_shl9_fu_796_p3;

assign p_shl9_fu_796_p3 = {{tmp_19_fu_792_p1}, {3'd0}};

assign p_shl_cast_fu_1883_p1 = p_shl_fu_1876_p3;

assign p_shl_fu_1876_p3 = {{tmp_42_reg_2010}, {3'd0}};

assign ret_V_0_1_fu_262_p3 = {{tmp_6_fu_258_p1}, {2'd0}};

assign ret_V_0_2_cast_fu_350_p1 = $signed(ret_V_0_2_fu_344_p2);

assign ret_V_0_2_fu_344_p2 = (p_shl1_cast_fu_328_p1 - p_shl2_cast_fu_340_p1);

assign ret_V_0_3_fu_410_p3 = {{tmp_9_fu_406_p1}, {2'd0}};

assign ret_V_1_1_fu_508_p3 = {{tmp_14_fu_504_p1}, {4'd0}};

assign ret_V_1_2_cast_fu_660_p1 = $signed(ret_V_1_2_fu_654_p2);

assign ret_V_1_2_fu_654_p2 = (p_shl5_cast_fu_638_p1 - p_shl6_cast_fu_650_p1);

assign ret_V_1_3_fu_720_p3 = {{tmp_17_fu_716_p1}, {4'd0}};

assign ret_V_1_4_fu_758_p3 = {{tmp_18_fu_754_p1}, {2'd0}};

assign ret_V_1_fu_470_p3 = {{tmp_13_fu_466_p1}, {2'd0}};

assign ret_V_2_1_cast_fu_972_p1 = $signed(ret_V_2_1_fu_966_p2);

assign ret_V_2_1_fu_966_p2 = (p_shl13_cast_fu_950_p1 - p_shl14_cast_fu_962_p1);

assign ret_V_2_2_fu_1056_p2 = (p_shl32_cast_fu_1040_p1 + p_shl33_cast_fu_1052_p1);

assign ret_V_2_3_cast_fu_1144_p1 = $signed(ret_V_2_3_fu_1138_p2);

assign ret_V_2_3_fu_1138_p2 = (p_shl28_cast_fu_1122_p1 - p_shl29_cast_fu_1134_p1);

assign ret_V_2_4_cast_fu_1234_p1 = $signed(ret_V_2_4_fu_1228_p2);

assign ret_V_2_4_fu_1228_p2 = (p_shl24_cast_fu_1212_p1 - p_shl25_cast_fu_1224_p1);

assign ret_V_2_cast_fu_826_p1 = $signed(ret_V_2_fu_820_p2);

assign ret_V_2_fu_820_p2 = (p_shl9_cast_fu_804_p1 - p_shl10_cast_fu_816_p1);

assign ret_V_3_1_fu_1332_p3 = {{tmp_30_fu_1328_p1}, {4'd0}};

assign ret_V_3_2_cast_fu_1400_p1 = $signed(ret_V_3_2_fu_1394_p2);

assign ret_V_3_2_fu_1394_p2 = (p_shl20_cast_fu_1378_p1 - p_shl21_cast_fu_1390_p1);

assign ret_V_3_3_fu_1460_p3 = {{tmp_34_fu_1456_p1}, {4'd0}};

assign ret_V_3_4_fu_1498_p3 = {{tmp_36_fu_1494_p1}, {2'd0}};

assign ret_V_3_fu_1294_p3 = {{tmp_28_fu_1290_p1}, {2'd0}};

assign ret_V_414_1_fu_1678_p3 = {{tmp_39_fu_1674_p1}, {2'd0}};

assign ret_V_414_2_cast_fu_1872_p1 = $signed(ret_V_414_2_fu_1866_p2);

assign ret_V_414_2_fu_1866_p2 = (p_shl16_cast_fu_1851_p1 - p_shl17_cast_fu_1862_p1);

assign ret_V_414_3_fu_1730_p3 = {{tmp_43_fu_1726_p1}, {2'd0}};

assign ret_V_4_0_1_fu_280_p3 = {{tmp_2_fu_270_p4}, {2'd0}};

assign ret_V_4_0_2_cast_fu_394_p1 = $signed(ret_V_4_0_2_fu_388_p2);

assign ret_V_4_0_2_fu_388_p2 = (p_shl3_cast_fu_372_p1 - p_shl4_cast_fu_384_p1);

assign ret_V_4_0_3_fu_428_p3 = {{tmp_8_fu_418_p4}, {2'd0}};

assign ret_V_4_1_1_fu_526_p3 = {{tmp_1_fu_516_p4}, {4'd0}};

assign ret_V_4_1_2_cast_fu_704_p1 = $signed(ret_V_4_1_2_fu_698_p2);

assign ret_V_4_1_2_fu_698_p2 = (p_shl7_cast_fu_682_p1 - p_shl8_cast_fu_694_p1);

assign ret_V_4_1_3_fu_738_p3 = {{tmp_10_fu_728_p4}, {4'd0}};

assign ret_V_4_1_4_fu_776_p3 = {{tmp_12_fu_766_p4}, {2'd0}};

assign ret_V_4_1_fu_488_p3 = {{tmp_s_fu_478_p4}, {2'd0}};

assign ret_V_4_2_1_cast_fu_1016_p1 = $signed(ret_V_4_2_1_fu_1010_p2);

assign ret_V_4_2_1_fu_1010_p2 = (p_shl34_cast_fu_994_p1 - p_shl35_cast_fu_1006_p1);

assign ret_V_4_2_2_fu_1096_p2 = (p_shl30_cast_fu_1080_p1 + p_shl31_cast_fu_1092_p1);

assign ret_V_4_2_3_cast_fu_1188_p1 = $signed(ret_V_4_2_3_fu_1182_p2);

assign ret_V_4_2_3_fu_1182_p2 = (p_shl26_cast_fu_1166_p1 - p_shl27_cast_fu_1178_p1);

assign ret_V_4_2_4_cast_fu_1278_p1 = $signed(ret_V_4_2_4_fu_1272_p2);

assign ret_V_4_2_4_fu_1272_p2 = (p_shl22_cast_fu_1256_p1 - p_shl23_cast_fu_1268_p1);

assign ret_V_4_2_cast_fu_870_p1 = $signed(ret_V_4_2_fu_864_p2);

assign ret_V_4_2_fu_864_p2 = (p_shl11_cast_fu_848_p1 - p_shl12_cast_fu_860_p1);

assign ret_V_4_3_1_fu_1350_p3 = {{tmp_31_fu_1340_p4}, {4'd0}};

assign ret_V_4_3_2_cast_fu_1444_p1 = $signed(ret_V_4_3_2_fu_1438_p2);

assign ret_V_4_3_2_fu_1438_p2 = (p_shl18_cast_fu_1422_p1 - p_shl19_cast_fu_1434_p1);

assign ret_V_4_3_3_fu_1478_p3 = {{tmp_35_fu_1468_p4}, {4'd0}};

assign ret_V_4_3_4_fu_1516_p3 = {{tmp_37_fu_1506_p4}, {2'd0}};

assign ret_V_4_3_fu_1312_p3 = {{tmp_29_fu_1302_p4}, {2'd0}};

assign ret_V_4_4_1_fu_1696_p3 = {{tmp_40_fu_1686_p4}, {2'd0}};

assign ret_V_4_4_2_cast_fu_1904_p1 = $signed(ret_V_4_4_2_fu_1898_p2);

assign ret_V_4_4_2_fu_1898_p2 = (p_shl_cast_fu_1883_p1 - p_shl15_cast_fu_1894_p1);

assign ret_V_4_4_3_fu_1748_p3 = {{tmp_44_fu_1738_p4}, {2'd0}};

assign tmp10_cast_fu_890_p1 = tmp10_fu_884_p2;

assign tmp10_fu_884_p2 = (tmp_71_1_3_cast_cast_fu_746_p1 + tmp_71_1_4_cast_cast_fu_784_p1);

assign tmp11_fu_910_p2 = (accum2_1_1_1_fu_620_p2 + tmp_72_1_2_cast_fu_712_p1);

assign tmp12_fu_926_p2 = (tmp13_cast_fu_922_p1 + tmp_72_2_cast_cast_fu_906_p1);

assign tmp13_cast_fu_922_p1 = tmp13_fu_916_p2;

assign tmp13_fu_916_p2 = (tmp_72_1_3_cast_cast_fu_750_p1 + tmp_72_1_4_cast_cast_fu_788_p1);

assign tmp14_fu_1818_p2 = (tmp16_reg_1979 + tmp15_reg_1974);

assign tmp15_fu_1550_p2 = (accum1_1_2_fu_900_p2 + tmp_71_2_1_cast_fu_1020_p1);

assign tmp16_fu_1562_p2 = (tmp17_fu_1556_p2 + tmp_71_2_3_cast_cast_fu_1192_p1);

assign tmp17_fu_1556_p2 = (tmp_71_2_4_cast_cast_fu_1282_p1 + tmp_71_3_2_cast_cast_fu_1448_p1);

assign tmp18_cast_fu_1822_p1 = tmp18_reg_1984;

assign tmp18_fu_1604_p2 = (tmp21_cast_fu_1600_p1 + tmp19_fu_1578_p2);

assign tmp19_fu_1578_p2 = (tmp20_cast_fu_1574_p1 + tmp_71_2_2_cast_cast_fu_1102_p1);

assign tmp1_cast_fu_544_p1 = tmp1_fu_538_p2;

assign tmp1_fu_538_p2 = (tmp_71_1_1_cast_cast_fu_534_p1 + accum1_1_0_1_cast_ca_fu_298_p1);

assign tmp20_cast_fu_1574_p1 = tmp20_fu_1568_p2;

assign tmp20_fu_1568_p2 = (tmp_71_3_1_cast_cast_fu_1358_p1 + tmp_71_3_3_cast_cast_fu_1486_p1);

assign tmp21_cast_fu_1600_p1 = tmp21_fu_1594_p2;

assign tmp21_fu_1594_p2 = (tmp22_cast_fu_1590_p1 + tmp_71_3_cast_cast_fu_1320_p1);

assign tmp22_cast_fu_1590_p1 = tmp22_fu_1584_p2;

assign tmp22_fu_1584_p2 = (tmp_71_3_4_cast_cast_fu_1524_p1 + tmp_71_4_cast_cast_fu_1546_p1);

assign tmp23_fu_1831_p2 = (tmp25_reg_1994 + tmp24_reg_1989);

assign tmp24_fu_1614_p2 = (accum2_1_2_fu_932_p2 + tmp_72_2_1_cast_fu_1024_p1);

assign tmp25_fu_1626_p2 = (tmp26_fu_1620_p2 + tmp_72_2_3_cast_cast_fu_1196_p1);

assign tmp26_fu_1620_p2 = (tmp_72_2_4_cast_cast_fu_1286_p1 + tmp_72_3_2_cast_cast_fu_1452_p1);

assign tmp27_cast_fu_1835_p1 = tmp27_reg_1999;

assign tmp27_fu_1668_p2 = (tmp30_cast_fu_1664_p1 + tmp28_fu_1642_p2);

assign tmp28_fu_1642_p2 = (tmp29_cast_fu_1638_p1 + tmp_72_2_2_cast_cast_fu_1106_p1);

assign tmp29_cast_fu_1638_p1 = tmp29_fu_1632_p2;

assign tmp29_fu_1632_p2 = (tmp_72_3_1_cast_cast_fu_1362_p1 + tmp_72_3_3_cast_cast_fu_1490_p1);

assign tmp2_cast_fu_570_p1 = tmp2_fu_564_p2;

assign tmp2_fu_564_p2 = (tmp3_cast_fu_560_p1 + tmp_71_0_3_cast_cast_fu_436_p1);

assign tmp30_cast_fu_1664_p1 = tmp30_fu_1658_p2;

assign tmp30_fu_1658_p2 = (tmp31_cast_fu_1654_p1 + tmp_72_3_cast_cast_fu_1324_p1);

assign tmp31_cast_fu_1654_p1 = tmp31_fu_1648_p2;

assign tmp31_fu_1648_p2 = (tmp_72_3_4_cast_cast_fu_1528_p1 + tmp_72_4_cast_cast_fu_1610_p1);

assign tmp32_fu_1916_p2 = (accum1_1_4_fu_1825_p2 + tmp_71_4_2_cast_cast_fu_1908_p1);

assign tmp33_cast_fu_1922_p1 = tmp33_reg_2016;

assign tmp33_fu_1792_p2 = (tmp34_cast_fu_1788_p1 + tmp_71_4_1_cast_cast_fu_1704_p1);

assign tmp34_cast_fu_1788_p1 = tmp34_fu_1782_p2;

assign tmp34_fu_1782_p2 = (tmp_71_4_3_cast_cast_fu_1756_p1 + tmp_71_4_4_cast_cast_fu_1778_p1);

assign tmp35_fu_1931_p2 = (accum2_1_4_fu_1838_p2 + tmp_72_4_2_cast_cast_fu_1912_p1);

assign tmp36_cast_fu_1937_p1 = tmp36_reg_2021;

assign tmp36_fu_1812_p2 = (tmp37_cast_fu_1808_p1 + tmp_72_4_1_cast_cast_fu_1708_p1);

assign tmp37_cast_fu_1808_p1 = tmp37_fu_1802_p2;

assign tmp37_fu_1802_p2 = (tmp_72_4_3_cast_cast_fu_1760_p1 + tmp_72_4_4_cast_cast_fu_1798_p1);

assign tmp3_cast_fu_560_p1 = tmp3_fu_554_p2;

assign tmp3_fu_554_p2 = (tmp_71_1_cast_cast_fu_496_p1 + tmp_71_0_4_cast_cast_fu_458_p1);

assign tmp4_fu_594_p2 = (tmp5_cast_fu_590_p1 + tmp_72_0_2_cast_fu_402_p1);

assign tmp5_cast_fu_590_p1 = tmp5_fu_584_p2;

assign tmp5_fu_584_p2 = (tmp_72_1_1_cast_cast_fu_580_p1 + accum2_1_0_1_cast_ca_fu_312_p1);

assign tmp6_cast_fu_616_p1 = tmp6_fu_610_p2;

assign tmp6_fu_610_p2 = (tmp7_cast_fu_606_p1 + tmp_72_0_3_cast_cast_fu_440_p1);

assign tmp7_cast_fu_606_p1 = tmp7_fu_600_p2;

assign tmp7_fu_600_p2 = (tmp_72_1_cast_cast_fu_500_p1 + tmp_72_0_4_cast_cast_fu_462_p1);

assign tmp8_fu_878_p2 = (accum1_1_1_1_fu_574_p2 + tmp_71_1_2_cast_fu_708_p1);

assign tmp9_fu_894_p2 = (tmp10_cast_fu_890_p1 + tmp_71_2_cast_cast_fu_874_p1);

assign tmp_10_fu_728_p4 = {{window_8_V_read[23:12]}};

assign tmp_11_fu_444_p1 = window_4_V_read[11:0];

assign tmp_12_fu_766_p4 = {{window_9_V_read[23:12]}};

assign tmp_13_fu_466_p1 = window_5_V_read[11:0];

assign tmp_14_fu_504_p1 = window_6_V_read[11:0];

assign tmp_15_fu_830_p4 = {{window_10_V_read[23:12]}};

assign tmp_16_fu_626_p1 = window_7_V_read[11:0];

assign tmp_17_fu_716_p1 = window_8_V_read[11:0];

assign tmp_18_fu_754_p1 = window_9_V_read[11:0];

assign tmp_19_fu_792_p1 = window_10_V_read[11:0];

assign tmp_1_fu_516_p4 = {{window_6_V_read[23:12]}};

assign tmp_20_fu_938_p1 = window_11_V_read[11:0];

assign tmp_21_fu_976_p4 = {{window_11_V_read[23:12]}};

assign tmp_22_fu_1028_p1 = window_12_V_read[11:0];

assign tmp_23_fu_1062_p4 = {{window_12_V_read[23:12]}};

assign tmp_24_fu_1110_p1 = window_13_V_read[11:0];

assign tmp_25_fu_1148_p4 = {{window_13_V_read[23:12]}};

assign tmp_26_fu_1200_p1 = window_14_V_read[11:0];

assign tmp_27_fu_1238_p4 = {{window_14_V_read[23:12]}};

assign tmp_28_fu_1290_p1 = window_15_V_read[11:0];

assign tmp_29_fu_1302_p4 = {{window_15_V_read[23:12]}};

assign tmp_2_fu_270_p4 = {{window_1_V_read[23:12]}};

assign tmp_30_fu_1328_p1 = window_16_V_read[11:0];

assign tmp_31_fu_1340_p4 = {{window_16_V_read[23:12]}};

assign tmp_32_fu_1366_p1 = window_17_V_read[11:0];

assign tmp_33_fu_1404_p4 = {{window_17_V_read[23:12]}};

assign tmp_34_fu_1456_p1 = window_18_V_read[11:0];

assign tmp_35_fu_1468_p4 = {{window_18_V_read[23:12]}};

assign tmp_36_fu_1494_p1 = window_19_V_read[11:0];

assign tmp_37_fu_1506_p4 = {{window_19_V_read[23:12]}};

assign tmp_38_fu_1532_p1 = window_20_V_read[11:0];

assign tmp_39_fu_1674_p1 = window_21_V_read[11:0];

assign tmp_3_fu_664_p4 = {{window_7_V_read[23:12]}};

assign tmp_40_fu_1686_p4 = {{window_21_V_read[23:12]}};

assign tmp_41_fu_1712_p1 = window_22_V_read[11:0];

assign tmp_43_fu_1726_p1 = window_23_V_read[11:0];

assign tmp_44_fu_1738_p4 = {{window_23_V_read[23:12]}};

assign tmp_45_fu_1764_p1 = window_24_V_read[11:0];

assign tmp_4_fu_236_p1 = window_0_V_read[11:0];

assign tmp_5_fu_354_p4 = {{window_2_V_read[23:12]}};

assign tmp_6_fu_258_p1 = window_1_V_read[11:0];

assign tmp_71_0_1_cast_fu_288_p1 = ret_V_0_1_fu_262_p3;

assign tmp_71_0_2_cast_fu_398_p1 = $unsigned(ret_V_0_2_cast_fu_350_p1);

assign tmp_71_0_3_cast_cast_fu_436_p1 = ret_V_0_3_fu_410_p3;

assign tmp_71_0_4_cast_cast_fu_458_p1 = tmp_11_fu_444_p1;

assign tmp_71_0_cast_fu_250_p1 = tmp_4_fu_236_p1;

assign tmp_71_1_1_cast_cast_fu_534_p1 = ret_V_1_1_fu_508_p3;

assign tmp_71_1_2_cast_fu_708_p1 = $unsigned(ret_V_1_2_cast_fu_660_p1);

assign tmp_71_1_3_cast_cast_fu_746_p1 = ret_V_1_3_fu_720_p3;

assign tmp_71_1_4_cast_cast_fu_784_p1 = ret_V_1_4_fu_758_p3;

assign tmp_71_1_cast_cast_fu_496_p1 = ret_V_1_fu_470_p3;

assign tmp_71_2_1_cast_fu_1020_p1 = $unsigned(ret_V_2_1_cast_fu_972_p1);

assign tmp_71_2_2_cast_cast_fu_1102_p1 = ret_V_2_2_fu_1056_p2;

assign tmp_71_2_3_cast_cast_fu_1192_p1 = $unsigned(ret_V_2_3_cast_fu_1144_p1);

assign tmp_71_2_4_cast_cast_fu_1282_p1 = $unsigned(ret_V_2_4_cast_fu_1234_p1);

assign tmp_71_2_cast_cast_fu_874_p1 = $unsigned(ret_V_2_cast_fu_826_p1);

assign tmp_71_3_1_cast_cast_fu_1358_p1 = ret_V_3_1_fu_1332_p3;

assign tmp_71_3_2_cast_cast_fu_1448_p1 = $unsigned(ret_V_3_2_cast_fu_1400_p1);

assign tmp_71_3_3_cast_cast_fu_1486_p1 = ret_V_3_3_fu_1460_p3;

assign tmp_71_3_4_cast_cast_fu_1524_p1 = ret_V_3_4_fu_1498_p3;

assign tmp_71_3_cast_cast_fu_1320_p1 = ret_V_3_fu_1294_p3;

assign tmp_71_4_1_cast_cast_fu_1704_p1 = ret_V_414_1_fu_1678_p3;

assign tmp_71_4_2_cast_cast_fu_1908_p1 = $unsigned(ret_V_414_2_cast_fu_1872_p1);

assign tmp_71_4_3_cast_cast_fu_1756_p1 = ret_V_414_3_fu_1730_p3;

assign tmp_71_4_4_cast_cast_fu_1778_p1 = tmp_45_fu_1764_p1;

assign tmp_71_4_cast_cast_fu_1546_p1 = tmp_38_fu_1532_p1;

assign tmp_72_0_1_cast_fu_302_p1 = ret_V_4_0_1_fu_280_p3;

assign tmp_72_0_2_cast_fu_402_p1 = $unsigned(ret_V_4_0_2_cast_fu_394_p1);

assign tmp_72_0_3_cast_cast_fu_440_p1 = ret_V_4_0_3_fu_428_p3;

assign tmp_72_0_4_cast_cast_fu_462_p1 = p_Result_8_0_4_fu_448_p4;

assign tmp_72_0_cast_fu_254_p1 = p_Result_8_fu_240_p4;

assign tmp_72_1_1_cast_cast_fu_580_p1 = ret_V_4_1_1_fu_526_p3;

assign tmp_72_1_2_cast_fu_712_p1 = $unsigned(ret_V_4_1_2_cast_fu_704_p1);

assign tmp_72_1_3_cast_cast_fu_750_p1 = ret_V_4_1_3_fu_738_p3;

assign tmp_72_1_4_cast_cast_fu_788_p1 = ret_V_4_1_4_fu_776_p3;

assign tmp_72_1_cast_cast_fu_500_p1 = ret_V_4_1_fu_488_p3;

assign tmp_72_2_1_cast_fu_1024_p1 = $unsigned(ret_V_4_2_1_cast_fu_1016_p1);

assign tmp_72_2_2_cast_cast_fu_1106_p1 = ret_V_4_2_2_fu_1096_p2;

assign tmp_72_2_3_cast_cast_fu_1196_p1 = $unsigned(ret_V_4_2_3_cast_fu_1188_p1);

assign tmp_72_2_4_cast_cast_fu_1286_p1 = $unsigned(ret_V_4_2_4_cast_fu_1278_p1);

assign tmp_72_2_cast_cast_fu_906_p1 = $unsigned(ret_V_4_2_cast_fu_870_p1);

assign tmp_72_3_1_cast_cast_fu_1362_p1 = ret_V_4_3_1_fu_1350_p3;

assign tmp_72_3_2_cast_cast_fu_1452_p1 = $unsigned(ret_V_4_3_2_cast_fu_1444_p1);

assign tmp_72_3_3_cast_cast_fu_1490_p1 = ret_V_4_3_3_fu_1478_p3;

assign tmp_72_3_4_cast_cast_fu_1528_p1 = ret_V_4_3_4_fu_1516_p3;

assign tmp_72_3_cast_cast_fu_1324_p1 = ret_V_4_3_fu_1312_p3;

assign tmp_72_4_1_cast_cast_fu_1708_p1 = ret_V_4_4_1_fu_1696_p3;

assign tmp_72_4_2_cast_cast_fu_1912_p1 = $unsigned(ret_V_4_4_2_cast_fu_1904_p1);

assign tmp_72_4_3_cast_cast_fu_1760_p1 = ret_V_4_4_3_fu_1748_p3;

assign tmp_72_4_4_cast_cast_fu_1798_p1 = p_Result_8_4_4_fu_1768_p4;

assign tmp_72_4_cast_cast_fu_1610_p1 = p_Result_8_4_fu_1536_p4;

assign tmp_7_fu_316_p1 = window_2_V_read[11:0];

assign tmp_8_fu_418_p4 = {{window_3_V_read[23:12]}};

assign tmp_9_fu_406_p1 = window_3_V_read[11:0];

assign tmp_fu_548_p2 = (tmp1_cast_fu_544_p1 + tmp_71_0_2_cast_fu_398_p1);

assign tmp_s_fu_478_p4 = {{window_5_V_read[23:12]}};

always @ (posedge ap_clk) begin
    tmp16_reg_1979[0] <= 1'b0;
    tmp25_reg_1994[0] <= 1'b0;
end

endmodule //hls_isotropic_kernel
