// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_LK,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.371000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=40,HLS_SYN_DSP=48,HLS_SYN_FF=8277,HLS_SYN_LUT=12009,HLS_VERSION=2018_3}" *)

module hls_LK (
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        inp1_img_TDATA,
        inp1_img_TLAST,
        inp2_img_TDATA,
        inp2_img_TLAST,
        vx_img_TDATA,
        vx_img_TLAST,
        vy_img_TDATA,
        vy_img_TLAST,
        inp1_img_TVALID,
        inp1_img_TREADY,
        inp2_img_TVALID,
        inp2_img_TREADY,
        vx_img_TVALID,
        vx_img_TREADY,
        vy_img_TVALID,
        vy_img_TREADY
);

parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1:0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [7:0] inp1_img_TDATA;
input  [0:0] inp1_img_TLAST;
input  [7:0] inp2_img_TDATA;
input  [0:0] inp2_img_TLAST;
output  [7:0] vx_img_TDATA;
output  [0:0] vx_img_TLAST;
output  [7:0] vy_img_TDATA;
output  [0:0] vy_img_TLAST;
input   inp1_img_TVALID;
output   inp1_img_TREADY;
input   inp2_img_TVALID;
output   inp2_img_TREADY;
output   vx_img_TVALID;
input   vx_img_TREADY;
output   vy_img_TVALID;
input   vy_img_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [15:0] height;
wire   [15:0] width;
wire    hls_twoIsotropicFilt_U0_ap_start;
wire    hls_twoIsotropicFilt_U0_ap_done;
wire    hls_twoIsotropicFilt_U0_ap_continue;
wire    hls_twoIsotropicFilt_U0_ap_idle;
wire    hls_twoIsotropicFilt_U0_ap_ready;
wire    hls_twoIsotropicFilt_U0_start_out;
wire    hls_twoIsotropicFilt_U0_start_write;
wire    hls_twoIsotropicFilt_U0_inp1_img_TREADY;
wire    hls_twoIsotropicFilt_U0_inp2_img_TREADY;
wire   [11:0] hls_twoIsotropicFilt_U0_out1_img_V_din;
wire    hls_twoIsotropicFilt_U0_out1_img_V_write;
wire   [11:0] hls_twoIsotropicFilt_U0_out2_img_V_din;
wire    hls_twoIsotropicFilt_U0_out2_img_V_write;
wire   [15:0] hls_twoIsotropicFilt_U0_height_out_din;
wire    hls_twoIsotropicFilt_U0_height_out_write;
wire   [15:0] hls_twoIsotropicFilt_U0_width_out_din;
wire    hls_twoIsotropicFilt_U0_width_out_write;
wire    hls_SpatialTemporalD_U0_ap_start;
wire    hls_SpatialTemporalD_U0_ap_done;
wire    hls_SpatialTemporalD_U0_ap_continue;
wire    hls_SpatialTemporalD_U0_ap_idle;
wire    hls_SpatialTemporalD_U0_ap_ready;
wire    hls_SpatialTemporalD_U0_start_out;
wire    hls_SpatialTemporalD_U0_start_write;
wire    hls_SpatialTemporalD_U0_inp1_img_V_read;
wire    hls_SpatialTemporalD_U0_inp2_img_V_read;
wire   [12:0] hls_SpatialTemporalD_U0_out_Ix_img_V_din;
wire    hls_SpatialTemporalD_U0_out_Ix_img_V_write;
wire   [12:0] hls_SpatialTemporalD_U0_out_Iy_img_V_din;
wire    hls_SpatialTemporalD_U0_out_Iy_img_V_write;
wire   [12:0] hls_SpatialTemporalD_U0_out_It_img_V_din;
wire    hls_SpatialTemporalD_U0_out_It_img_V_write;
wire    hls_SpatialTemporalD_U0_height_read;
wire    hls_SpatialTemporalD_U0_width_read;
wire   [15:0] hls_SpatialTemporalD_U0_height_out_din;
wire    hls_SpatialTemporalD_U0_height_out_write;
wire   [15:0] hls_SpatialTemporalD_U0_width_out_din;
wire    hls_SpatialTemporalD_U0_width_out_write;
wire    hls_ComputeIntegrals_U0_ap_start;
wire    hls_ComputeIntegrals_U0_ap_done;
wire    hls_ComputeIntegrals_U0_ap_continue;
wire    hls_ComputeIntegrals_U0_ap_idle;
wire    hls_ComputeIntegrals_U0_ap_ready;
wire    hls_ComputeIntegrals_U0_start_out;
wire    hls_ComputeIntegrals_U0_start_write;
wire    hls_ComputeIntegrals_U0_Ix_img_V_read;
wire    hls_ComputeIntegrals_U0_Iy_img_V_read;
wire    hls_ComputeIntegrals_U0_It_img_V_read;
wire   [33:0] hls_ComputeIntegrals_U0_A11_img_V_din;
wire    hls_ComputeIntegrals_U0_A11_img_V_write;
wire   [33:0] hls_ComputeIntegrals_U0_A12_img_V_din;
wire    hls_ComputeIntegrals_U0_A12_img_V_write;
wire   [33:0] hls_ComputeIntegrals_U0_A22_img_V_din;
wire    hls_ComputeIntegrals_U0_A22_img_V_write;
wire   [33:0] hls_ComputeIntegrals_U0_B1_img_V_din;
wire    hls_ComputeIntegrals_U0_B1_img_V_write;
wire   [33:0] hls_ComputeIntegrals_U0_B2_img_V_din;
wire    hls_ComputeIntegrals_U0_B2_img_V_write;
wire    hls_ComputeIntegrals_U0_height_read;
wire    hls_ComputeIntegrals_U0_width_read;
wire   [15:0] hls_ComputeIntegrals_U0_height_out_din;
wire    hls_ComputeIntegrals_U0_height_out_write;
wire   [15:0] hls_ComputeIntegrals_U0_width_out_din;
wire    hls_ComputeIntegrals_U0_width_out_write;
wire    hls_ComputeVectors_U0_ap_start;
wire    hls_ComputeVectors_U0_ap_done;
wire    hls_ComputeVectors_U0_ap_continue;
wire    hls_ComputeVectors_U0_ap_idle;
wire    hls_ComputeVectors_U0_ap_ready;
wire    hls_ComputeVectors_U0_A11_img_V_read;
wire    hls_ComputeVectors_U0_A12_img_V_read;
wire    hls_ComputeVectors_U0_A22_img_V_read;
wire    hls_ComputeVectors_U0_B1_img_V_read;
wire    hls_ComputeVectors_U0_B2_img_V_read;
wire   [7:0] hls_ComputeVectors_U0_vx_img_TDATA;
wire    hls_ComputeVectors_U0_vx_img_TVALID;
wire   [0:0] hls_ComputeVectors_U0_vx_img_TLAST;
wire   [7:0] hls_ComputeVectors_U0_vy_img_TDATA;
wire    hls_ComputeVectors_U0_vy_img_TVALID;
wire   [0:0] hls_ComputeVectors_U0_vy_img_TLAST;
wire    hls_ComputeVectors_U0_height_read;
wire    hls_ComputeVectors_U0_width_read;
wire   [31:0] hls_ComputeVectors_U0_ap_return;
wire    ap_sync_continue;
wire    flt1_img_channel_full_n;
wire   [11:0] flt1_img_channel_dout;
wire    flt1_img_channel_empty_n;
wire    flt2_img_channel_full_n;
wire   [11:0] flt2_img_channel_dout;
wire    flt2_img_channel_empty_n;
wire    height_c_full_n;
wire   [15:0] height_c_dout;
wire    height_c_empty_n;
wire    width_c_full_n;
wire   [15:0] width_c_dout;
wire    width_c_empty_n;
wire    Dx1_img_channel_full_n;
wire   [12:0] Dx1_img_channel_dout;
wire    Dx1_img_channel_empty_n;
wire    Dy1_img_channel_full_n;
wire   [12:0] Dy1_img_channel_dout;
wire    Dy1_img_channel_empty_n;
wire    Dt_img_channel_full_n;
wire   [12:0] Dt_img_channel_dout;
wire    Dt_img_channel_empty_n;
wire    height_c9_full_n;
wire   [15:0] height_c9_dout;
wire    height_c9_empty_n;
wire    width_c10_full_n;
wire   [15:0] width_c10_dout;
wire    width_c10_empty_n;
wire    A11_img_channel_full_n;
wire   [33:0] A11_img_channel_dout;
wire    A11_img_channel_empty_n;
wire    A12_img_channel_full_n;
wire   [33:0] A12_img_channel_dout;
wire    A12_img_channel_empty_n;
wire    A22_img_channel_full_n;
wire   [33:0] A22_img_channel_dout;
wire    A22_img_channel_empty_n;
wire    B1_img_channel_full_n;
wire   [33:0] B1_img_channel_dout;
wire    B1_img_channel_empty_n;
wire    B2_img_channel_full_n;
wire   [33:0] B2_img_channel_dout;
wire    B2_img_channel_empty_n;
wire    height_c11_full_n;
wire   [15:0] height_c11_dout;
wire    height_c11_empty_n;
wire    width_c12_full_n;
wire   [15:0] width_c12_dout;
wire    width_c12_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_hls_SpatialTemporalD_U0_din;
wire    start_for_hls_SpatialTemporalD_U0_full_n;
wire   [0:0] start_for_hls_SpatialTemporalD_U0_dout;
wire    start_for_hls_SpatialTemporalD_U0_empty_n;
wire   [0:0] start_for_hls_ComputeIntegrals_U0_din;
wire    start_for_hls_ComputeIntegrals_U0_full_n;
wire   [0:0] start_for_hls_ComputeIntegrals_U0_dout;
wire    start_for_hls_ComputeIntegrals_U0_empty_n;
wire   [0:0] start_for_hls_ComputeVectors_U0_din;
wire    start_for_hls_ComputeVectors_U0_full_n;
wire   [0:0] start_for_hls_ComputeVectors_U0_dout;
wire    start_for_hls_ComputeVectors_U0_empty_n;
wire    hls_ComputeVectors_U0_start_full_n;
wire    hls_ComputeVectors_U0_start_write;
wire   [31:0] ap_return;

hls_LK_CONTROL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
hls_LK_CONTROL_BUS_s_axi_U(
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(hls_ComputeVectors_U0_ap_return),
    .height(height),
    .width(width)
);

hls_twoIsotropicFilt hls_twoIsotropicFilt_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hls_twoIsotropicFilt_U0_ap_start),
    .start_full_n(start_for_hls_SpatialTemporalD_U0_full_n),
    .ap_done(hls_twoIsotropicFilt_U0_ap_done),
    .ap_continue(hls_twoIsotropicFilt_U0_ap_continue),
    .ap_idle(hls_twoIsotropicFilt_U0_ap_idle),
    .ap_ready(hls_twoIsotropicFilt_U0_ap_ready),
    .start_out(hls_twoIsotropicFilt_U0_start_out),
    .start_write(hls_twoIsotropicFilt_U0_start_write),
    .inp1_img_TDATA(inp1_img_TDATA),
    .inp1_img_TVALID(inp1_img_TVALID),
    .inp1_img_TREADY(hls_twoIsotropicFilt_U0_inp1_img_TREADY),
    .inp1_img_TLAST(inp1_img_TLAST),
    .inp2_img_TDATA(inp2_img_TDATA),
    .inp2_img_TVALID(inp2_img_TVALID),
    .inp2_img_TREADY(hls_twoIsotropicFilt_U0_inp2_img_TREADY),
    .inp2_img_TLAST(inp2_img_TLAST),
    .out1_img_V_din(hls_twoIsotropicFilt_U0_out1_img_V_din),
    .out1_img_V_full_n(flt1_img_channel_full_n),
    .out1_img_V_write(hls_twoIsotropicFilt_U0_out1_img_V_write),
    .out2_img_V_din(hls_twoIsotropicFilt_U0_out2_img_V_din),
    .out2_img_V_full_n(flt2_img_channel_full_n),
    .out2_img_V_write(hls_twoIsotropicFilt_U0_out2_img_V_write),
    .height(height),
    .width(width),
    .height_out_din(hls_twoIsotropicFilt_U0_height_out_din),
    .height_out_full_n(height_c_full_n),
    .height_out_write(hls_twoIsotropicFilt_U0_height_out_write),
    .width_out_din(hls_twoIsotropicFilt_U0_width_out_din),
    .width_out_full_n(width_c_full_n),
    .width_out_write(hls_twoIsotropicFilt_U0_width_out_write)
);

hls_SpatialTemporalD hls_SpatialTemporalD_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hls_SpatialTemporalD_U0_ap_start),
    .start_full_n(start_for_hls_ComputeIntegrals_U0_full_n),
    .ap_done(hls_SpatialTemporalD_U0_ap_done),
    .ap_continue(hls_SpatialTemporalD_U0_ap_continue),
    .ap_idle(hls_SpatialTemporalD_U0_ap_idle),
    .ap_ready(hls_SpatialTemporalD_U0_ap_ready),
    .start_out(hls_SpatialTemporalD_U0_start_out),
    .start_write(hls_SpatialTemporalD_U0_start_write),
    .inp1_img_V_dout(flt1_img_channel_dout),
    .inp1_img_V_empty_n(flt1_img_channel_empty_n),
    .inp1_img_V_read(hls_SpatialTemporalD_U0_inp1_img_V_read),
    .inp2_img_V_dout(flt2_img_channel_dout),
    .inp2_img_V_empty_n(flt2_img_channel_empty_n),
    .inp2_img_V_read(hls_SpatialTemporalD_U0_inp2_img_V_read),
    .out_Ix_img_V_din(hls_SpatialTemporalD_U0_out_Ix_img_V_din),
    .out_Ix_img_V_full_n(Dx1_img_channel_full_n),
    .out_Ix_img_V_write(hls_SpatialTemporalD_U0_out_Ix_img_V_write),
    .out_Iy_img_V_din(hls_SpatialTemporalD_U0_out_Iy_img_V_din),
    .out_Iy_img_V_full_n(Dy1_img_channel_full_n),
    .out_Iy_img_V_write(hls_SpatialTemporalD_U0_out_Iy_img_V_write),
    .out_It_img_V_din(hls_SpatialTemporalD_U0_out_It_img_V_din),
    .out_It_img_V_full_n(Dt_img_channel_full_n),
    .out_It_img_V_write(hls_SpatialTemporalD_U0_out_It_img_V_write),
    .height_dout(height_c_dout),
    .height_empty_n(height_c_empty_n),
    .height_read(hls_SpatialTemporalD_U0_height_read),
    .width_dout(width_c_dout),
    .width_empty_n(width_c_empty_n),
    .width_read(hls_SpatialTemporalD_U0_width_read),
    .height_out_din(hls_SpatialTemporalD_U0_height_out_din),
    .height_out_full_n(height_c9_full_n),
    .height_out_write(hls_SpatialTemporalD_U0_height_out_write),
    .width_out_din(hls_SpatialTemporalD_U0_width_out_din),
    .width_out_full_n(width_c10_full_n),
    .width_out_write(hls_SpatialTemporalD_U0_width_out_write)
);

hls_ComputeIntegrals hls_ComputeIntegrals_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hls_ComputeIntegrals_U0_ap_start),
    .start_full_n(start_for_hls_ComputeVectors_U0_full_n),
    .ap_done(hls_ComputeIntegrals_U0_ap_done),
    .ap_continue(hls_ComputeIntegrals_U0_ap_continue),
    .ap_idle(hls_ComputeIntegrals_U0_ap_idle),
    .ap_ready(hls_ComputeIntegrals_U0_ap_ready),
    .start_out(hls_ComputeIntegrals_U0_start_out),
    .start_write(hls_ComputeIntegrals_U0_start_write),
    .Ix_img_V_dout(Dx1_img_channel_dout),
    .Ix_img_V_empty_n(Dx1_img_channel_empty_n),
    .Ix_img_V_read(hls_ComputeIntegrals_U0_Ix_img_V_read),
    .Iy_img_V_dout(Dy1_img_channel_dout),
    .Iy_img_V_empty_n(Dy1_img_channel_empty_n),
    .Iy_img_V_read(hls_ComputeIntegrals_U0_Iy_img_V_read),
    .It_img_V_dout(Dt_img_channel_dout),
    .It_img_V_empty_n(Dt_img_channel_empty_n),
    .It_img_V_read(hls_ComputeIntegrals_U0_It_img_V_read),
    .A11_img_V_din(hls_ComputeIntegrals_U0_A11_img_V_din),
    .A11_img_V_full_n(A11_img_channel_full_n),
    .A11_img_V_write(hls_ComputeIntegrals_U0_A11_img_V_write),
    .A12_img_V_din(hls_ComputeIntegrals_U0_A12_img_V_din),
    .A12_img_V_full_n(A12_img_channel_full_n),
    .A12_img_V_write(hls_ComputeIntegrals_U0_A12_img_V_write),
    .A22_img_V_din(hls_ComputeIntegrals_U0_A22_img_V_din),
    .A22_img_V_full_n(A22_img_channel_full_n),
    .A22_img_V_write(hls_ComputeIntegrals_U0_A22_img_V_write),
    .B1_img_V_din(hls_ComputeIntegrals_U0_B1_img_V_din),
    .B1_img_V_full_n(B1_img_channel_full_n),
    .B1_img_V_write(hls_ComputeIntegrals_U0_B1_img_V_write),
    .B2_img_V_din(hls_ComputeIntegrals_U0_B2_img_V_din),
    .B2_img_V_full_n(B2_img_channel_full_n),
    .B2_img_V_write(hls_ComputeIntegrals_U0_B2_img_V_write),
    .height_dout(height_c9_dout),
    .height_empty_n(height_c9_empty_n),
    .height_read(hls_ComputeIntegrals_U0_height_read),
    .width_dout(width_c10_dout),
    .width_empty_n(width_c10_empty_n),
    .width_read(hls_ComputeIntegrals_U0_width_read),
    .height_out_din(hls_ComputeIntegrals_U0_height_out_din),
    .height_out_full_n(height_c11_full_n),
    .height_out_write(hls_ComputeIntegrals_U0_height_out_write),
    .width_out_din(hls_ComputeIntegrals_U0_width_out_din),
    .width_out_full_n(width_c12_full_n),
    .width_out_write(hls_ComputeIntegrals_U0_width_out_write)
);

hls_ComputeVectors hls_ComputeVectors_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hls_ComputeVectors_U0_ap_start),
    .ap_done(hls_ComputeVectors_U0_ap_done),
    .ap_continue(hls_ComputeVectors_U0_ap_continue),
    .ap_idle(hls_ComputeVectors_U0_ap_idle),
    .ap_ready(hls_ComputeVectors_U0_ap_ready),
    .A11_img_V_dout(A11_img_channel_dout),
    .A11_img_V_empty_n(A11_img_channel_empty_n),
    .A11_img_V_read(hls_ComputeVectors_U0_A11_img_V_read),
    .A12_img_V_dout(A12_img_channel_dout),
    .A12_img_V_empty_n(A12_img_channel_empty_n),
    .A12_img_V_read(hls_ComputeVectors_U0_A12_img_V_read),
    .A22_img_V_dout(A22_img_channel_dout),
    .A22_img_V_empty_n(A22_img_channel_empty_n),
    .A22_img_V_read(hls_ComputeVectors_U0_A22_img_V_read),
    .B1_img_V_dout(B1_img_channel_dout),
    .B1_img_V_empty_n(B1_img_channel_empty_n),
    .B1_img_V_read(hls_ComputeVectors_U0_B1_img_V_read),
    .B2_img_V_dout(B2_img_channel_dout),
    .B2_img_V_empty_n(B2_img_channel_empty_n),
    .B2_img_V_read(hls_ComputeVectors_U0_B2_img_V_read),
    .vx_img_TDATA(hls_ComputeVectors_U0_vx_img_TDATA),
    .vx_img_TVALID(hls_ComputeVectors_U0_vx_img_TVALID),
    .vx_img_TREADY(vx_img_TREADY),
    .vx_img_TLAST(hls_ComputeVectors_U0_vx_img_TLAST),
    .vy_img_TDATA(hls_ComputeVectors_U0_vy_img_TDATA),
    .vy_img_TVALID(hls_ComputeVectors_U0_vy_img_TVALID),
    .vy_img_TREADY(vy_img_TREADY),
    .vy_img_TLAST(hls_ComputeVectors_U0_vy_img_TLAST),
    .height_dout(height_c11_dout),
    .height_empty_n(height_c11_empty_n),
    .height_read(hls_ComputeVectors_U0_height_read),
    .width_dout(width_c12_dout),
    .width_empty_n(width_c12_empty_n),
    .width_read(hls_ComputeVectors_U0_width_read),
    .ap_return(hls_ComputeVectors_U0_ap_return)
);

fifo_w12_d10_A flt1_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_twoIsotropicFilt_U0_out1_img_V_din),
    .if_full_n(flt1_img_channel_full_n),
    .if_write(hls_twoIsotropicFilt_U0_out1_img_V_write),
    .if_dout(flt1_img_channel_dout),
    .if_empty_n(flt1_img_channel_empty_n),
    .if_read(hls_SpatialTemporalD_U0_inp1_img_V_read)
);

fifo_w12_d10_A flt2_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_twoIsotropicFilt_U0_out2_img_V_din),
    .if_full_n(flt2_img_channel_full_n),
    .if_write(hls_twoIsotropicFilt_U0_out2_img_V_write),
    .if_dout(flt2_img_channel_dout),
    .if_empty_n(flt2_img_channel_empty_n),
    .if_read(hls_SpatialTemporalD_U0_inp2_img_V_read)
);

fifo_w16_d2_A height_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_twoIsotropicFilt_U0_height_out_din),
    .if_full_n(height_c_full_n),
    .if_write(hls_twoIsotropicFilt_U0_height_out_write),
    .if_dout(height_c_dout),
    .if_empty_n(height_c_empty_n),
    .if_read(hls_SpatialTemporalD_U0_height_read)
);

fifo_w16_d2_A width_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_twoIsotropicFilt_U0_width_out_din),
    .if_full_n(width_c_full_n),
    .if_write(hls_twoIsotropicFilt_U0_width_out_write),
    .if_dout(width_c_dout),
    .if_empty_n(width_c_empty_n),
    .if_read(hls_SpatialTemporalD_U0_width_read)
);

fifo_w13_d10_A Dx1_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_SpatialTemporalD_U0_out_Ix_img_V_din),
    .if_full_n(Dx1_img_channel_full_n),
    .if_write(hls_SpatialTemporalD_U0_out_Ix_img_V_write),
    .if_dout(Dx1_img_channel_dout),
    .if_empty_n(Dx1_img_channel_empty_n),
    .if_read(hls_ComputeIntegrals_U0_Ix_img_V_read)
);

fifo_w13_d10_A Dy1_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_SpatialTemporalD_U0_out_Iy_img_V_din),
    .if_full_n(Dy1_img_channel_full_n),
    .if_write(hls_SpatialTemporalD_U0_out_Iy_img_V_write),
    .if_dout(Dy1_img_channel_dout),
    .if_empty_n(Dy1_img_channel_empty_n),
    .if_read(hls_ComputeIntegrals_U0_Iy_img_V_read)
);

fifo_w13_d10_A Dt_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_SpatialTemporalD_U0_out_It_img_V_din),
    .if_full_n(Dt_img_channel_full_n),
    .if_write(hls_SpatialTemporalD_U0_out_It_img_V_write),
    .if_dout(Dt_img_channel_dout),
    .if_empty_n(Dt_img_channel_empty_n),
    .if_read(hls_ComputeIntegrals_U0_It_img_V_read)
);

fifo_w16_d2_A height_c9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_SpatialTemporalD_U0_height_out_din),
    .if_full_n(height_c9_full_n),
    .if_write(hls_SpatialTemporalD_U0_height_out_write),
    .if_dout(height_c9_dout),
    .if_empty_n(height_c9_empty_n),
    .if_read(hls_ComputeIntegrals_U0_height_read)
);

fifo_w16_d2_A width_c10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_SpatialTemporalD_U0_width_out_din),
    .if_full_n(width_c10_full_n),
    .if_write(hls_SpatialTemporalD_U0_width_out_write),
    .if_dout(width_c10_dout),
    .if_empty_n(width_c10_empty_n),
    .if_read(hls_ComputeIntegrals_U0_width_read)
);

fifo_w34_d10_A A11_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_ComputeIntegrals_U0_A11_img_V_din),
    .if_full_n(A11_img_channel_full_n),
    .if_write(hls_ComputeIntegrals_U0_A11_img_V_write),
    .if_dout(A11_img_channel_dout),
    .if_empty_n(A11_img_channel_empty_n),
    .if_read(hls_ComputeVectors_U0_A11_img_V_read)
);

fifo_w34_d10_A A12_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_ComputeIntegrals_U0_A12_img_V_din),
    .if_full_n(A12_img_channel_full_n),
    .if_write(hls_ComputeIntegrals_U0_A12_img_V_write),
    .if_dout(A12_img_channel_dout),
    .if_empty_n(A12_img_channel_empty_n),
    .if_read(hls_ComputeVectors_U0_A12_img_V_read)
);

fifo_w34_d10_A A22_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_ComputeIntegrals_U0_A22_img_V_din),
    .if_full_n(A22_img_channel_full_n),
    .if_write(hls_ComputeIntegrals_U0_A22_img_V_write),
    .if_dout(A22_img_channel_dout),
    .if_empty_n(A22_img_channel_empty_n),
    .if_read(hls_ComputeVectors_U0_A22_img_V_read)
);

fifo_w34_d10_A B1_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_ComputeIntegrals_U0_B1_img_V_din),
    .if_full_n(B1_img_channel_full_n),
    .if_write(hls_ComputeIntegrals_U0_B1_img_V_write),
    .if_dout(B1_img_channel_dout),
    .if_empty_n(B1_img_channel_empty_n),
    .if_read(hls_ComputeVectors_U0_B1_img_V_read)
);

fifo_w34_d10_A B2_img_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_ComputeIntegrals_U0_B2_img_V_din),
    .if_full_n(B2_img_channel_full_n),
    .if_write(hls_ComputeIntegrals_U0_B2_img_V_write),
    .if_dout(B2_img_channel_dout),
    .if_empty_n(B2_img_channel_empty_n),
    .if_read(hls_ComputeVectors_U0_B2_img_V_read)
);

fifo_w16_d2_A height_c11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_ComputeIntegrals_U0_height_out_din),
    .if_full_n(height_c11_full_n),
    .if_write(hls_ComputeIntegrals_U0_height_out_write),
    .if_dout(height_c11_dout),
    .if_empty_n(height_c11_empty_n),
    .if_read(hls_ComputeVectors_U0_height_read)
);

fifo_w16_d2_A width_c12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hls_ComputeIntegrals_U0_width_out_din),
    .if_full_n(width_c12_full_n),
    .if_write(hls_ComputeIntegrals_U0_width_out_write),
    .if_dout(width_c12_dout),
    .if_empty_n(width_c12_empty_n),
    .if_read(hls_ComputeVectors_U0_width_read)
);

start_for_hls_SpatialTemporalD_U0 start_for_hls_SpatialTemporalD_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hls_SpatialTemporalD_U0_din),
    .if_full_n(start_for_hls_SpatialTemporalD_U0_full_n),
    .if_write(hls_twoIsotropicFilt_U0_start_write),
    .if_dout(start_for_hls_SpatialTemporalD_U0_dout),
    .if_empty_n(start_for_hls_SpatialTemporalD_U0_empty_n),
    .if_read(hls_SpatialTemporalD_U0_ap_ready)
);

start_for_hls_ComputeIntegrals_U0 start_for_hls_ComputeIntegrals_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hls_ComputeIntegrals_U0_din),
    .if_full_n(start_for_hls_ComputeIntegrals_U0_full_n),
    .if_write(hls_SpatialTemporalD_U0_start_write),
    .if_dout(start_for_hls_ComputeIntegrals_U0_dout),
    .if_empty_n(start_for_hls_ComputeIntegrals_U0_empty_n),
    .if_read(hls_ComputeIntegrals_U0_ap_ready)
);

start_for_hls_ComputeVectors_U0 start_for_hls_ComputeVectors_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hls_ComputeVectors_U0_din),
    .if_full_n(start_for_hls_ComputeVectors_U0_full_n),
    .if_write(hls_ComputeIntegrals_U0_start_write),
    .if_dout(start_for_hls_ComputeVectors_U0_dout),
    .if_empty_n(start_for_hls_ComputeVectors_U0_empty_n),
    .if_read(hls_ComputeVectors_U0_ap_ready)
);

assign ap_done = hls_ComputeVectors_U0_ap_done;

assign ap_idle = (hls_twoIsotropicFilt_U0_ap_idle & hls_SpatialTemporalD_U0_ap_idle & hls_ComputeVectors_U0_ap_idle & hls_ComputeIntegrals_U0_ap_idle);

assign ap_ready = hls_twoIsotropicFilt_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = hls_ComputeVectors_U0_ap_done;

assign ap_sync_ready = hls_twoIsotropicFilt_U0_ap_ready;

assign hls_ComputeIntegrals_U0_ap_continue = 1'b1;

assign hls_ComputeIntegrals_U0_ap_start = start_for_hls_ComputeIntegrals_U0_empty_n;

assign hls_ComputeVectors_U0_ap_continue = 1'b1;

assign hls_ComputeVectors_U0_ap_start = start_for_hls_ComputeVectors_U0_empty_n;

assign hls_ComputeVectors_U0_start_full_n = 1'b1;

assign hls_ComputeVectors_U0_start_write = 1'b0;

assign hls_SpatialTemporalD_U0_ap_continue = 1'b1;

assign hls_SpatialTemporalD_U0_ap_start = start_for_hls_SpatialTemporalD_U0_empty_n;

assign hls_twoIsotropicFilt_U0_ap_continue = 1'b1;

assign hls_twoIsotropicFilt_U0_ap_start = ap_start;

assign inp1_img_TREADY = hls_twoIsotropicFilt_U0_inp1_img_TREADY;

assign inp2_img_TREADY = hls_twoIsotropicFilt_U0_inp2_img_TREADY;

assign start_for_hls_ComputeIntegrals_U0_din = 1'b1;

assign start_for_hls_ComputeVectors_U0_din = 1'b1;

assign start_for_hls_SpatialTemporalD_U0_din = 1'b1;

assign vx_img_TDATA = hls_ComputeVectors_U0_vx_img_TDATA;

assign vx_img_TLAST = hls_ComputeVectors_U0_vx_img_TLAST;

assign vx_img_TVALID = hls_ComputeVectors_U0_vx_img_TVALID;

assign vy_img_TDATA = hls_ComputeVectors_U0_vy_img_TDATA;

assign vy_img_TLAST = hls_ComputeVectors_U0_vy_img_TLAST;

assign vy_img_TVALID = hls_ComputeVectors_U0_vy_img_TVALID;

endmodule //hls_LK
